async page => {
  const base='__BASE_URL__',output='__OUTPUT_DIR__',prefix='Home QA '+Date.now();
  const assert=(value,message)=>{if(!value)throw Error(message);};
  const stages=[],errors=[],requests=[],writes=[];let stage='fixture setup';
  const headers={'X-PMC-Request':'local-console'};
  page.on('pageerror',error=>errors.push(error.message));
  page.on('request',request=>{if(request.url().includes('/api/'))requests.push(request.url());if(request.method()==='POST')writes.push(request.url());});
  // CLI batches stop at native JS prompts. Keep the production handlers intact
  // and provide deterministic answers in this isolated browser context only.
  await page.addInitScript(()=>{
    window.__homeDialogs=[];window.__homeAnswer=null;
    window.confirm=message=>{window.__homeDialogs.push(message);return window.__homeAnswer===true;};
    window.prompt=message=>{window.__homeDialogs.push(message);return window.__homeAnswer;};
    window.alert=message=>window.__homeDialogs.push(message);
  });
  const answer=value=>page.evaluate(value=>{window.__homeAnswer=value;},value);
  const json=async response=>{assert(response.ok(),await response.text());return response.json();};
  const saved=[];
  const home=page.locator('#project-home'),nav=home.getByRole('navigation',{name:'Home navigation'}),dialog=page.locator('#workflow-dialog');
  const search=()=>home.getByRole('searchbox',{name:'Search saved projects'});
  const row=id=>home.locator(`[data-project-id="${id}"]`);
  const ready=()=>page.waitForFunction(()=>document.querySelector('.home-project-table')?.getAttribute('aria-busy')==='false');
  const menu=async(id,name,value)=>{await answer(value);await row(id).getByRole('button',{name:'More',exact:true}).click();await home.getByRole('menuitem',{name,exact:true}).click();await ready();};
  const close=async()=>{await dialog.press('Escape');await dialog.waitFor({state:'hidden'});};
  try{
    for(let i=0;i<6;i++)saved.push(await json(await page.request.post(base+'/api/projects',{headers,data:{design:{name:prefix+' '+i,project_context:i===0?'inch':'metric',block:{length:203.2+i,width:127,height:101.6,material:'Isolated browser fixture'}}}})));
    const target=saved[0],id=target.project_id;
    await page.setViewportSize({width:1366,height:768});await page.goto(base);await ready();
    await home.locator('[aria-label="Material"][data-loaded="true"]').waitFor();
    await home.getByText('ENGINEERING DB READY',{exact:true}).waitFor();
    stage='Home layout, real summaries and materials';
    assert(await nav.isVisible(),'Home sidebar is missing');
    for(const name of ['Drawing','Hydraulic Nets','Schematic','Engineering Review'])assert(await nav.getByRole('button',{name,exact:true}).isDisabled(),name+' is enabled without a project');
    assert(await home.locator('tbody tr[data-project-id]').count()===5,'Expected five recent rows');
    const materialRows=(await json(await page.request.get(base+'/api/materials'))).items.filter(row=>row.active);
    const actualMaterials=await home.getByLabel('Material',{exact:true}).locator('option').evaluateAll(nodes=>nodes.filter(n=>n.value).map(n=>({id:n.value,name:n.textContent})));
    assert(JSON.stringify(actualMaterials)===JSON.stringify(materialRows.map(row=>({id:row.id,name:row.display_name}))),'Material options differ from SQLite API');
    assert(materialRows.length>0,'Fixture has no active material records');
    for(const [width,height]of [[1366,768],[900,800]]){
      await page.setViewportSize({width,height});
      const dimensions=await home.evaluate(node=>({page:document.documentElement.scrollWidth,client:innerWidth,search:node.querySelector('.home-library-input').getBoundingClientRect().bottom,content:node.querySelector('.home-content').scrollWidth,container:node.querySelector('.home-content').clientWidth}));
      assert(dimensions.page<=width&&dimensions.content<=dimensions.container+1,'Home overflows horizontally at '+width);
      assert(dimensions.search<=height,'Library search is below the initial viewport at '+width);
      await page.screenshot({path:`${output}/launchpad-${width}x${height}.png`});
    }
    await page.setViewportSize({width:1366,height:768});
    await search().fill(prefix+' 0');await row(id).waitFor();
    const summary=(await json(await page.request.get(base+'/api/projects'))).find(item=>item.id===id);
    const cells=await row(id).locator('td').allTextContents();
    assert(cells[1]==='203.2 × 127 × 101.6'&&cells[2]===String(summary.features)&&cells[3]===summary.status,'Project row changed stored dimensions, feature count or status');
    await search().fill(prefix);assert(await home.getByRole('button',{name:'Next',exact:true}).isVisible(),'Project pagination missing');
    await home.getByRole('button',{name:'Next',exact:true}).click();assert(await home.locator('tbody tr[data-project-id]').count()===1,'Project pagination omitted a row');
    await home.getByRole('button',{name:'Previous',exact:true}).click();
    assert(!requests.some(url=>/\/api\/(preview|preview-solid|build)(?:[?\/]|$)/.test(url)),'Home requested engineering work for thumbnails');
    assert(writes.length===0,'Home initialization wrote project data');stages.push(stage);

    stage='Existing workflows, immediate prefill and library without a project';
    const quick=home.locator('.home-quick');
    await home.getByLabel('Unit context').selectOption('inch');await quick.getByLabel('Project name',{exact:true}).fill(prefix+' draft');
    await quick.getByLabel('Length / in',{exact:true}).fill('8');await quick.getByLabel('Width / in',{exact:true}).fill('5');await quick.getByLabel('Height / in',{exact:true}).fill('4');
    await quick.getByLabel('Material',{exact:true}).selectOption(materialRows[0].id);
    await home.getByRole('button',{name:'Continue Engineering Setup'}).click();
    await dialog.getByRole('heading',{name:'New Manifold · 1 / 5 · Block'}).waitFor();
    assert(!await nav.isVisible(),'Home sidebar is visible in the existing workflow');
    assert(await dialog.getByLabel('Project context',{exact:true}).inputValue()==='inch','Unit prefill lost');
    assert(await dialog.getByLabel('Project name',{exact:true}).inputValue()===prefix+' draft','Name prefill lost');
    assert(await dialog.getByLabel('Length / in',{exact:true}).inputValue()==='8','Envelope prefill lost');
    assert(await dialog.getByLabel('Block material / grade').inputValue()===materialRows[0].display_name,'Material prefill lost');
    await close();assert(await home.getByRole('button',{name:'Continue Engineering Setup'}).evaluate(node=>node===document.activeElement),'Native dialog close did not return focus');
    await nav.getByRole('button',{name:'New Manifold',exact:true}).click();await dialog.getByRole('heading',{name:'New Manifold · 1 / 5 · Block'}).waitFor();await close();
    await home.getByRole('button',{name:'Open AI Design',exact:true}).click();await dialog.getByRole('heading',{name:/AI Design/}).waitFor();await close();
    await home.getByRole('button',{name:'Import Project',exact:true}).click();await dialog.getByRole('heading',{name:/Import/}).waitFor();await close();
    await nav.getByRole('button',{name:'Engineering Library',exact:true}).click();
    await dialog.getByRole('heading',{name:'Engineering Library · SQLite'}).waitFor();
    await dialog.getByText('Browse definitions here. Open or create a manifold to place a feature.').waitFor();
    await page.waitForFunction(()=>!document.getElementById('workflow-content').textContent.includes('Loading SQLite'));
    assert(await dialog.locator('button').filter({hasText:/^Place Cavity$/}).evaluateAll(nodes=>nodes.every(node=>node.disabled)),'Library can place a feature without a draft');
    assert(!await page.locator('#workflow-error').innerText(),'Library failed without a draft');await close();
    const librarySearch=home.getByRole('searchbox',{name:'Search engineering library'});
    await librarySearch.fill('M8');await home.locator('.home-library-result').first().waitFor();
    assert(await home.locator('.home-library-result').count()<=6,'Library search returned more than six rows');
    assert((await home.locator('.home-result-type').allTextContents()).includes('Thread'),'Real thread result missing');
    for(const path of ['catalog','cartridges','threads'])assert(requests.some(url=>url.includes('/api/'+path+'?')&&url.includes('q=M8')),'Library did not query '+path);
    await librarySearch.fill('');assert(await home.locator('.home-library-result').count()===0,'Cleared search kept old results');stages.push(stage);

    stage='Project management, archive filter and exact-name delete';
    await search().fill(prefix+' 0');
    await row(id).getByRole('button',{name:'More'}).press('Enter');await home.getByRole('menuitem',{name:'Rename',exact:true}).waitFor();
    await page.keyboard.press('ArrowDown');assert(await home.getByRole('menuitem',{name:'Duplicate',exact:true}).evaluate(node=>node===document.activeElement),'More menu arrow navigation failed');
    await page.keyboard.press('Escape');assert(await row(id).getByRole('button',{name:'More'}).evaluate(node=>node===document.activeElement),'More menu Escape did not restore focus');
    const renamed=prefix+' 0 renamed';await menu(id,'Rename',renamed);await row(id).getByText(renamed,{exact:true}).waitFor();
    await menu(id,'Duplicate',prefix+' 0 copy');
    const copy=(await json(await page.request.get(base+'/api/projects'))).find(item=>item.name===prefix+' 0 copy');assert(copy,'Duplicate not saved');
    await menu(id,'Archive',null);await row(id).waitFor({state:'hidden'});
    await home.getByRole('button',{name:'Show archived projects'}).click();await ready();await row(id).waitFor();
    await menu(id,'Restore',null);await row(id).waitFor({state:'hidden'});
    await home.getByRole('button',{name:'Show active projects'}).click();await ready();await row(id).waitFor();
    await menu(copy.id,'Delete permanently','wrong name');assert(await row(copy.id).isVisible(),'Mismatched-name deletion succeeded');
    await menu(copy.id,'Delete permanently',null);assert(await row(copy.id).isVisible(),'Cancelled deletion succeeded');
    await menu(copy.id,'Delete permanently',copy.name);await row(copy.id).waitFor({state:'hidden'});
    assert(!(await json(await page.request.get(base+'/api/projects'))).some(item=>item.id===copy.id),'Confirmed deletion did not remove project');stages.push(stage);

    stage='Five-step draft, Home return, dirty protection and Drawing handoff';
    await quick.getByLabel('Project name',{exact:true}).fill(prefix+' draft');
    await home.getByRole('button',{name:'Continue Engineering Setup'}).click();
    await dialog.getByRole('button',{name:'Next · Nets and ports'}).click();
    await dialog.getByLabel('Net IDs (comma separated)').fill('P');await dialog.getByLabel('Net IDs (comma separated)').press('Tab');
    await dialog.getByRole('button',{name:'Next · Cartridges and cavities'}).click();
    await dialog.getByRole('button',{name:'Continue without cavities'}).click();await dialog.getByRole('button',{name:'Next · Review'}).click();
    await dialog.getByRole('button',{name:'Create editable draft'}).click();await page.locator('#viewport').waitFor({state:'visible'});
    assert(!await nav.isVisible(),'Home sidebar leaked into Model');
    assert(await page.locator('#dirty-dot').getAttribute('aria-label')==='Unsaved draft','Created draft is not dirty');
    await page.locator('#projects-open').click();await ready();assert(await nav.isVisible(),'Home sidebar did not return');
    assert(!await nav.getByRole('button',{name:'Drawing',exact:true}).isDisabled(),'Current draft Drawing entry disabled');
    await nav.getByRole('button',{name:'Model',exact:true}).click();assert(await page.locator('#project-name').innerText()===prefix+' draft','Model entry lost draft');
    await page.locator('#projects-open').click();await ready();await search().fill(renamed);await answer(false);
    await row(id).getByRole('button',{name:'Open CAD'}).click();assert(await nav.isVisible(),'Dirty project open did not respect cancellation');
    await row(id).getByRole('button',{name:'Drawing',exact:true}).click();assert(await nav.isVisible(),'Dirty Drawing did not respect cancellation');
    const messages=await page.evaluate(()=>window.__homeDialogs);assert(messages.some(message=>message.includes('Discard the current unsaved draft'))&&messages.some(message=>message.includes('Leave the unsaved manifold draft')),'Dirty confirmations missing');
    await home.getByRole('button',{name:'Return to current draft'}).click();await page.locator('#save-project').click();
    await page.waitForFunction(()=>document.querySelector('#dirty-dot')?.getAttribute('aria-label')==='Draft saved');
    await page.locator('#projects-open').click();await ready();await row(id).getByRole('button',{name:'Open CAD'}).click();
    await page.waitForFunction(name=>document.getElementById('project-name')?.textContent===name,renamed);assert(!await nav.isVisible(),'Saved-project open kept Home sidebar');
    await page.locator('#projects-open').click();await ready();
    await row(id).getByRole('button',{name:'Drawing',exact:true}).click();await page.waitForURL(base+'/drawing.html?project='+id);
    assert(await page.locator('.home-sidebar').count()===0,'Home sidebar leaked into Drawing');stages.push(stage);

    stage='Empty/error/retry, stale responses and service failures';
    await page.route(base+'/api/projects',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Isolated project service unavailable'})}));
    await page.goto(base);await home.getByRole('button',{name:'Retry loading projects'}).waitFor();
    await quick.getByLabel('Project name',{exact:true}).fill('Keep setup during retry');
    await page.unroute(base+'/api/projects');await home.getByRole('button',{name:'Retry loading projects'}).click();await ready();
    assert(await quick.getByLabel('Project name',{exact:true}).inputValue()==='Keep setup during retry','Retry reset Quick Setup');
    await search().fill('nonexistent-'+prefix);await home.getByText('No matching projects. Try another name.').waitFor();
    await page.route(base+'/api/projects',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));await page.reload();await ready();
    await home.getByText('No saved projects yet. Start with Quick block setup or import a project.').waitFor();await page.unroute(base+'/api/projects');
    let release;const held=new Promise(resolve=>release=resolve);let first=true;
    await page.route(base+'/api/projects',async route=>{if(first){first=false;await held;await route.fulfill({status:200,contentType:'application/json',body:'[]'});}else await route.continue();});
    await page.reload();await home.getByRole('button',{name:'Show archived projects'}).click();await ready();release();
    await page.waitForTimeout(100);assert(await home.getByRole('heading',{name:'Archived projects',exact:true}).isVisible(),'Old response replaced the archive view');await page.unroute(base+'/api/projects');
    for(const path of ['health','catalog/manifest','materials'])await page.route(base+'/api/'+path,route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Isolated unavailable'})}));
    await page.reload();await home.getByText('SERVICE UNAVAILABLE',{exact:true}).waitFor();await home.getByText('ENGINEERING DB UNAVAILABLE',{exact:true}).waitFor();
    assert(await home.getByLabel('Material',{exact:true}).isDisabled(),'Unavailable materials appeared usable');
    for(const path of ['health','catalog/manifest','materials'])await page.unroute(base+'/api/'+path);
    await page.reload();await ready();await home.getByText('ENGINEERING DB READY',{exact:true}).waitFor();
    assert(!writes.some(url=>/\/api\/(build|ai\/.*(?:analyze|analysis))/.test(url)),'Home acceptance started a build or external AI analysis');
    assert(errors.length===0,'Page errors: '+errors.join('; '));stages.push(stage);
    return {passed:true,stages,pageErrors:errors,fixturePrefix:prefix,projectIds:saved.map(item=>item.project_id),screenshots:['launchpad-1366x768.png','launchpad-900x800.png']};
  }catch(error){await page.screenshot({path:output+'/failure.png'});return {passed:false,stage,error:String(error),stages,pageErrors:errors,fixturePrefix:prefix};}
}
