async page => {
  const base='__BASE_URL__',output='__OUTPUT_DIR__',stages=[],errors=[];let stage='load';
  const assert=(value,message)=>{if(!value)throw Error(message);};
  page.on('pageerror',error=>errors.push(error.message));
  const dialog=page.locator('#workflow-dialog');
  const api=async path=>{const response=await page.request.get(base+path);assert(response.ok(),path+': '+response.status());return response.json();};
  const screenshot=async name=>{await dialog.evaluate(node=>{node.scrollTop=0;});await page.screenshot({path:output+'/'+name+'.png',fullPage:false});};
  const category=async name=>{await dialog.locator('.library-category-grid > *').filter({has:page.getByRole('heading',{name,exact:true})}).getByRole('button',{name:'Open →',exact:true}).click();};
  const back=async()=>{await dialog.getByRole('button',{name:'Back to Engineering Library',exact:true}).click();};
  const openCartridge=async query=>{await dialog.getByLabel('Search cartridge model or manufacturer').fill(query);await dialog.getByRole('button',{name:'View Cartridge',exact:true}).first().waitFor();
    const results=await api('/api/cartridges?q='+encodeURIComponent(query)+'&limit=100');assert(results.items.length,'No search result '+query);
    await dialog.getByRole('heading',{name:results.items[0].manufacturer+' '+results.items[0].model,exact:true}).waitFor();
    await dialog.getByRole('button',{name:'View Cartridge',exact:true}).first().click();await dialog.getByRole('heading',{name:'Technical Knowledge · Identity',exact:true}).waitFor();return results.items[0];};
  try{
    await page.setViewportSize({width:1440,height:1000});await page.goto(base);await page.getByText('ENGINEERING DB READY',{exact:true}).waitFor();
    const secure=await page.evaluate(()=>isSecureContext);assert(secure===base.includes('127.0.0.1'),'Secure context mismatch');
    stage='Dashboard and projectless browse';await page.getByRole('button',{name:'Engineering Library',exact:true}).click();await dialog.locator('.library-category-grid').waitFor();assert(await dialog.locator('.library-category-grid > *').count()===8,'Category count');await page.waitForFunction(()=>!document.querySelector('#workflow-content').textContent.includes('Loading record count…'));await screenshot('dashboard');stages.push(stage);
    stage='Cartridge summary, evidence paging and source links';await category('Cartridges');const cartridge=await openCartridge('Sun CBDH');const expected=await api('/api/cartridges/'+cartridge.id+'/technical');assert(expected.counts.evidence>20,'Need substantial real technical evidence');
    await dialog.getByRole('heading',{name:'Hydraulic Performance',exact:true}).waitFor();assert(await dialog.getByRole('button',{name:/^(Place|Bind|Use)/}).count()===0,'Technical detail offers an execution action');
    const cavities=await api('/api/cartridges/'+cartridge.id+'/cavities');assert(cavities.length>0,'Expected unchanged compatibility');assert((await dialog.innerText()).includes('Confirmed / Execution-safe cavities'),'Compatibility section missing');
    await dialog.getByRole('button',{name:'Load technical evidence',exact:true}).click();await dialog.getByText('20 / '+expected.counts.evidence+' technical evidence',{exact:true}).waitFor();await dialog.getByRole('button',{name:'More technical evidence',exact:true}).click();await dialog.getByText('40 / '+expected.counts.evidence+' technical evidence',{exact:true}).waitFor();
    assert(await dialog.locator('a[href^="https://"],a[href^="http://"]').count()>0,'Source link unavailable');await screenshot('cartridge-evidence');stages.push(stage);
    stage='Conflict sides and resolution';assert(expected.counts.conflicts>0,'Need a real conflict');await dialog.getByRole('button',{name:'Load technical conflicts',exact:true}).click();await dialog.getByText(/Evidence A ·/).first().waitFor();await dialog.getByText(/Evidence B ·/).first().waitFor();await screenshot('conflicts');stages.push(stage);
    stage='Identity ambiguity';await dialog.getByRole('button',{name:'Back to Cartridges',exact:true}).click();assert(await dialog.getByLabel('Search cartridge model or manufacturer').inputValue()==='Sun CBDH','Search state lost');await openCartridge('IDENTITY_AMBIGUOUS');await dialog.getByText('Identity attribution is unresolved. Technical values are not automatically inherited from a similar model.',{exact:true}).waitFor();await screenshot('ambiguous');stages.push(stage);
    stage='Relation-only identity';await dialog.getByRole('button',{name:'Back to Cartridges',exact:true}).click();await openCartridge('D2E1-X');await dialog.getByText('Exact technical parameter evidence was not established in this research pass. Relationship evidence remains available.',{exact:true}).waitFor();assert(await dialog.getByRole('button',{name:/^(Place|Bind|Use)/}).count()===0,'Relation-only permission');await screenshot('relation-only');stages.push(stage);
    stage='Materials, treatment and stock separation';await dialog.getByRole('button',{name:'Back to Cartridges',exact:true}).click();await back();await category('Materials & Stock');const materialCard=dialog.locator('.library-card').filter({has:page.getByRole('heading',{name:'6061 T6',exact:true})});await materialCard.getByRole('button',{name:'View Detail',exact:true}).click();await dialog.getByRole('heading',{name:'Surface Treatments',exact:true}).waitFor();await dialog.getByRole('heading',{name:'Engineering Stock',exact:true}).waitFor();await dialog.getByRole('heading',{name:'Supplier / Research Stock Evidence',exact:true}).waitFor();await dialog.getByRole('button',{name:'Load supplier listings',exact:true}).click();await dialog.getByText(/LISTED_SIZE/).first().waitFor();await dialog.getByRole('button',{name:'Load technical evidence',exact:true}).click();await dialog.getByText('Evidence ID:',{exact:false}).first().waitFor();await screenshot('material');stages.push(stage);
    stage='Guided cavity and external-port selection remain direct';await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Continue Engineering Setup',exact:true}).click();await dialog.getByRole('heading',{name:'New Manifold · 1 / 5 · Block',exact:true}).waitFor();await dialog.getByLabel('Material',{exact:true}).selectOption({label:'Aluminum'});await dialog.getByRole('button',{name:'Next · Nets and ports',exact:true}).click();await dialog.getByLabel('P · Port source',{exact:true}).selectOption('standard');await dialog.getByRole('button',{name:'Use for P',exact:true}).first().waitFor();assert(!(await dialog.innerText()).includes('Available for browsing'),'Port selection incorrectly opens Dashboard');await page.screenshot({path:output+'/guided-port.png'});await dialog.getByRole('button',{name:'Use for P',exact:true}).first().click();await dialog.getByRole('button',{name:'Change P definition',exact:true}).waitFor();await dialog.getByRole('button',{name:'Next · Cartridges and cavities',exact:true}).click();await dialog.getByRole('button',{name:'Select cavity',exact:true}).first().waitFor();assert(!(await dialog.innerText()).includes('Available for browsing'),'Cavity selection incorrectly opens Dashboard');await page.screenshot({path:output+'/guided-cavity.png'});stages.push(stage);
    assert(errors.length===0,'Browser errors: '+errors.join('; '));return {passed:true,base,secureContext:secure,stages,errors};
  }catch(error){await page.screenshot({path:output+'/failure.png'});return {passed:false,base,stage,error:error.message,stages,errors};}
}
