import '../ui-tokens.css';
import './style.css';
import {createDrawingShell} from './shell.js';

createDrawingShell();

const $=id=>document.getElementById(id),clone=value=>structuredClone(value);
const projectId=new URLSearchParams(location.search).get('project');
let project,doc,edit,sheetId,selection=null,dirty=false,busy=false,history=[],future=[],renderEpoch=0,jobId=null,tableMetrics={};
const tableRowSelection={};
const usesPmc=()=>['pmc3069','pmc3092'].includes(edit?.template.layout);
let zoom=1,pan=[24,24],sheetSize=[594,420],pick=null,drag=null;
const base=()=>`/api/drawings/${projectId}`,url=()=>`${base()}/${doc.id}`;
function el(tag,text,cls){const node=document.createElement(tag);if(text!=null)node.textContent=text;if(cls)node.className=cls;return node;}
function button(parent,label,fn,cls){const b=el('button',label,cls);b.type='button';b.onclick=()=>{b.disabled=true;return Promise.resolve().then(fn).catch(fail).finally(()=>{b.disabled=false;controls();});};parent.append(b);return b;}
function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':'';$('message').setAttribute('role',error?'alert':'status');if(error)$('message').focus();}
function fail(error){message(error.message||String(error),true);if($('modal').open)$('modal-error').textContent=error.message||String(error);}
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-PMC-Request':'local-console'},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:Array.isArray(data.detail)?data.detail.map(i=>i.msg).join('; '):'Drawing request failed');return data;}
$('properties').onsubmit=e=>e.preventDefault();
function controls(){const locked=!doc||doc.status==='Released'||busy;for(const id of ['save','dimension','text','leader','view','table','schematic','sheet-add','update','release'])$(id).disabled=locked;for(const id of ['metadata','history','duplicate','revision','pdf'])$(id).disabled=!doc||busy;$('undo').disabled=locked||!history.length;$('redo').disabled=locked||!future.length;$('create').disabled=busy;for(const e of $('properties').querySelectorAll('input,textarea,select,button'))e.disabled=locked;$('document-state').textContent=doc?`${edit.metadata.number} · Rev ${edit.metadata.revision} · ${doc.status}${dirty?' · Unsaved':''}${doc.source_current?'':' · SOURCE CHANGED'}`:'Select or create a drawing';}
function recoveryKey(){return `pmc-drawing:${projectId}:${doc.id}`;}
function remember(){if(!doc)return;try{if(dirty)localStorage.setItem(recoveryKey(),JSON.stringify({revision:doc.revision,edit}));else localStorage.removeItem(recoveryKey());}catch{message('Browser recovery storage is unavailable. Save the drawing to retain changes.',true);}}
function changed(fn){if(!doc||doc.status==='Released'||busy)return;const previous=clone(edit);try{fn();history.push(previous);if(history.length>100)history.shift();future=[];dirty=true;remember();controls();tree();properties();requestRender();}catch(e){edit=previous;fail(e);}}
function findItem(id=selection){for(const key of ['views','annotations','tables','schematics','sheets']){const value=edit?.[key].find(i=>i.id===id);if(value)return {key,value};}return null;}
function selected(id){selection=id;tree();properties();highlight();}
function highlight(){for(const node of $('paper-container').querySelectorAll('g[data-item]'))node.classList.toggle('selected',node.dataset.item===selection);}
function modal(title,build){$('modal-title').textContent=title;$('modal-body').replaceChildren();$('modal-error').textContent='';build($('modal-body'));$('modal').showModal();}
$('modal-close').onclick=()=>$('modal').close();
function field(parent,label,value,onchange,type='text',options=null){const row=el('label',null,'field'+(type==='checkbox'?' check':''));row.append(el('span',label));const input=el(options?'select':type==='textarea'?'textarea':'input');input.setAttribute('aria-label',label);if(options)for(const [v,text]of options.map(o=>Array.isArray(o)?o:[o,o])){const opt=el('option',text);opt.value=v;input.append(opt);}else if(type!=='textarea')input.type=type;if(type==='checkbox')input.checked=!!value;else input.value=value??'';input.onchange=()=>onchange(type==='checkbox'?input.checked:type==='number'?Number(input.value):input.value);row.append(input);parent.append(row);return input;}
function property(label,key,type='text',options=null){const target=findItem()?.value;return field($('properties'),label,target[key],v=>changed(()=>target[key]=v),type,options);}
function requiredTableRows(table){return tableMetrics[table.id]?.required_physical_rows??1;}
function anchorLabel(key){if(key.startsWith('B:'))return 'Block corner '+key.slice(2);const raw=key.startsWith('F:')?key.slice(2):key,feature=raw.split(':')[0],row=Object.values(doc.table_sources||{}).flat().find(item=>item.id===feature),suffix=raw.includes(':step:')?' · machining '+raw.split(':step:')[1].replaceAll(':',' '):raw.endsWith(':end')?' · depth end':'';return (row?.label||'Engineering reference')+suffix;}
function positionProperties(target){for(const [index,label]of ['Paper X / offset X (mm)','Paper Y / offset Y (mm)'].entries())field($('properties'),label,target.position[index],v=>changed(()=>target.position[index]=v),'number');}
function properties(){const panel=$('properties');panel.replaceChildren();if(!edit)return;const item=findItem();$('properties-title').textContent=item?item.value.id:'Title block & document';
 if(!item){for(const [key,label]of [['number','Drawing number'],['title','Drawing title'],['revision','Revision label'],['customer','Customer'],['designed_by','Design by'],['drawn_by','Drawn by'],['checked_by','Checked by'],['approved_by','Approved by'],['date','Drawing date'],['revision_note','Revision description'],['notes','Drawing notes']])field(panel,label,edit.metadata[key],v=>changed(()=>edit.metadata[key]=v),['notes','revision_note'].includes(key)?'textarea':'text');field(panel,'Quantity',edit.metadata.quantity??1,v=>changed(()=>edit.metadata.quantity=v),'number');if(usesPmc()){for(const [i,band]of ['1–6','>6–30','>30–120','>120–315','>315–1000','>1000–2000','>2000'].entries())field(panel,'Linear tolerance '+band,edit.template.linear_tolerances[i],v=>changed(()=>edit.template.linear_tolerances[i]=v));}if(usesPmc())panel.append(el('p','PMC standard: A2 landscape · dimensions and tolerance bands in mm.','muted'));else field(panel,'Display units',edit.metadata.unit,v=>changed(()=>edit.metadata.unit=v),'text',['mm','inch']);for(const [key,label]of [['company','Company'],['address','Company address'],['website','Website'],['telephone','Telephone'],['fax','Fax'],['email','Email'],['standard_notes','Standard notes'],['general_tolerance','General tolerances']].filter(([key])=>key!=='general_tolerance'||!usesPmc()))field(panel,label,edit.template[key],v=>changed(()=>edit.template[key]=v),key.includes('notes')||key.includes('tolerance')?'textarea':'text');field(panel,'Show PMC logo',edit.template.show_logo??true,v=>changed(()=>edit.template.show_logo=v),'checkbox');field(panel,'I reviewed template notes and tolerances',edit.template.tolerance_confirmed,v=>changed(()=>edit.template.tolerance_confirmed=v),'checkbox');button(panel,'Save presentation as template',()=>modal('Save reusable drawing template',body=>{let name='PMC custom template';field(body,'Template name',name,v=>name=v);body.append(el('p','Saves sheets, view arrangement, table presentation and standard notes. Engineering identity and schematic assets stay with their source project.'));button(body,'Save template',async()=>{if(dirty)await save();await api(url()+'/template',{expected_revision:doc.revision,name});$('modal').close();message('Template saved. It is available in Create Drawing.');},'primary');}));panel.append(el('p',`Source manifold revision ${doc.source.design_revision} · build ${doc.source.build_id}`,'muted'));panel.append(el('p','Material, dimensions and product specifications follow the source manifold. Edit those in Manifold Studio.','muted'));
 }else{const {key,value}=item;if(value.position)positionProperties(value);if(key==='views'){property('View title','title');property('Scale','scale','number');property('Show hidden geometry','hidden','checkbox');property('Show centerlines','centerlines','checkbox');if(value.projection.startsWith('section-'))property('Section coordinate (mm); regenerate after change','section_at','number');}
 if(key==='annotations'){if(value.kind!=='dimension')property('Text','text','textarea');property('Text height (mm)','height','number');if(value.kind==='dimension'){field(panel,'Measurement',value.measure,v=>changed(()=>{value.measure=v;if(!['x','y'].includes(v))value.ordinate=false;value.anchors=['x','y','aligned'].includes(v)?[value.anchors[0],value.anchors[1]||'B:100']:[value.anchors[0]];}),'text',['x','y','aligned','diameter','radius','depth','angle']);property('Decimal places','precision','number');if(['x','y'].includes(value.measure))property('Ordinate dimensions','ordinate','checkbox');}if(value.anchors.length){panel.append(el('p','Source: '+value.anchors.map(anchorLabel).join(' → '),'muted'));button(panel,'Rebind engineering reference',()=>bindModal(value));}}
 if(key==='tables'){const sourceRows=doc.table_sources?.[value.kind]||[];if(sourceRows.length){let rowId=sourceRows.some(r=>r.id===tableRowSelection[value.id])?tableRowSelection[value.id]:sourceRows[0].id;const rowsBox=el('section');rowsBox.append(el('h3','Edit a row remark'));let remark;field(rowsBox,'Source row',rowId,v=>{rowId=v;tableRowSelection[value.id]=v;remark.value=value.remarks[v]||'';},'text',sourceRows.map(r=>[r.id,r.label]));remark=field(rowsBox,'Selected row remark',value.remarks[rowId]||'',v=>changed(()=>{if(v)value.remarks[rowId]=v;else delete value.remarks[rowId];}),'textarea');panel.append(rowsBox);}property('Table width (mm)','width','number');property('Minimum row height (mm)','row_height','number');property('Text height (mm)','height','number');const required=requiredTableRows(value);field(panel,'Displayed rows',value.display_rows??required,v=>changed(()=>{if(v<required)throw Error(`${required} rows required for the selected source groups.`);value.display_rows=v;}),'number');button(panel,'Fit rows to content',async()=>{const result=await api(url()+'/render',{edit,sheet:sheetId});tableMetrics=result.table_metrics||{};changed(()=>value.display_rows=requiredTableRows(value));});panel.append(el('p',`${required} physical row${required===1?'':'s'} required for the selected source groups. Additional displayed rows remain intentionally blank.`,'muted'));const advanced=el('details');advanced.append(el('summary','Advanced · Source pagination'));panel.append(advanced);field(advanced,'Start source group',value.start,v=>changed(()=>value.start=v),'number');field(advanced,'Source groups on this table',value.count,v=>changed(()=>value.count=v),'number');field(advanced,'Source ordering (internal IDs, one per line)',value.order.join('\n'),v=>changed(()=>value.order=v.split('\n').map(i=>i.trim()).filter(Boolean)),'textarea');field(advanced,'Remarks (internal ID = note, one per line)',Object.entries(value.remarks).map(([k,v])=>k+' = '+v).join('\n'),v=>changed(()=>{value.remarks={};for(const line of v.split('\n')){const i=line.indexOf('=');if(i>0)value.remarks[line.slice(0,i).trim()]=line.slice(i+1).trim();}}),'textarea');panel.append(el('p','Specification cells are generated from the fixed engineering source. Adjust presentation and remarks here.','muted'));button(panel,'Continue table on new sheet',()=>changed(()=>{const s={id:uid('sheet'),title:'Table continued',size:'A2',landscape:true};edit.sheets.push(s);edit.tables.push({...clone(value),id:uid('table'),sheet:s.id,position:[20,35],start:value.start+value.count});sheetId=s.id;}));}
 if(key==='schematics'){property('Width (mm)','width','number');property('Height (mm)','height','number');property('PDF page (zero based)','page','number');for(const [i,label]of ['Crop left (0–1)','Crop top (0–1)','Crop right (0–1)','Crop bottom (0–1)'].entries())field(panel,label,value.crop[i],v=>changed(()=>value.crop[i]=v),'number');}
 if(key==='sheets'){property('Sheet title','title');if(usesPmc())panel.append(el('p','PMC standard uses A2 landscape (594 × 420 mm).','muted'));else{property('Sheet size','size','text',['A4','A3','A2','A1','A0']);property('Landscape','landscape','checkbox');}const actions=el('div',null,'properties-actions');for(const [label,delta]of [['Move sheet earlier',-1],['Move sheet later',1]])button(actions,label,()=>changed(()=>{const i=edit.sheets.indexOf(value),j=i+delta;if(j>=0&&j<edit.sheets.length)[edit.sheets[i],edit.sheets[j]]=[edit.sheets[j],edit.sheets[i]];}));panel.append(actions);}
 if('visible'in value)property('Visible','visible','checkbox');if(key!=='sheets')field(panel,'Place on sheet',value.sheet,v=>changed(()=>{value.sheet=v;if(key==='views')for(const a of edit.annotations.filter(a=>a.view===value.id))a.sheet=v;sheetId=v;}),'text',edit.sheets.map(s=>[s.id,s.title||s.id]));const actions=el('div',null,'properties-actions');button(actions,'Delete selected',deleteSelected,'danger');panel.append(actions);}
 if(doc.status==='Released'||busy)for(const e of panel.querySelectorAll('input,textarea,select,button'))e.disabled=true;
}
function tree(){if(!edit)return;$('sheets').replaceChildren();edit.sheets.forEach((s,i)=>{const b=button($('sheets'),`${String(i+1).padStart(2,'0')} · ${s.title||s.id}`,()=>{sheetId=s.id;selected(s.id);requestRender(true);},'tree-button'+(s.id===sheetId?' active':''));b.title=s.id;});$('objects').replaceChildren();for(const key of ['views','annotations','tables','schematics'])for(const item of edit[key].filter(i=>i.sheet===sheetId)){const b=button($('objects'),item.title||item.text||(item.kind!=='dimension'&&doc.anchors[item.anchors?.[0]]?.label)||item.id,()=>selected(item.id),'tree-button'+(selection===item.id?' active':''));b.append(el('small',key==='annotations'?item.kind:key.slice(0,-1)));}}
function paintTransform(){$('paper-container').style.width=sheetSize[0]+'px';$('paper-container').style.height=sheetSize[1]+'px';$('paper-container').style.transform=`translate(${pan[0]}px,${pan[1]}px) scale(${zoom})`;$('zoom-value').textContent=Math.round(zoom*100)+'%';}
function fit(){const rect=$('paper-viewport').getBoundingClientRect();zoom=Math.max(.2,Math.min((rect.width-40)/sheetSize[0],(rect.height-40)/sheetSize[1]));pan=[(rect.width-sheetSize[0]*zoom)/2,(rect.height-sheetSize[1]*zoom)/2];paintTransform();}
let renderTimer;
function requestRender(fitting=false){clearTimeout(renderTimer);const epoch=++renderEpoch;renderTimer=setTimeout(()=>renderPaper(epoch,fitting).catch(fail),80);}
function installViewHitAreas(){
  const views=new Set(edit.views.filter(view=>view.sheet===sheetId&&view.visible!==false).map(view=>view.id));
  for(const group of $('paper-container').querySelectorAll('g[data-item]')){
    if(!views.has(group.dataset.item))continue;
    const bounds=group.getBBox();
    if(![bounds.x,bounds.y,bounds.width,bounds.height].every(Number.isFinite)||bounds.width<=0||bounds.height<=0)continue;
    const rect=document.createElementNS('http://www.w3.org/2000/svg','rect');
    rect.setAttribute('x',String(bounds.x));rect.setAttribute('y',String(bounds.y));
    rect.setAttribute('width',String(bounds.width));rect.setAttribute('height',String(bounds.height));
    rect.setAttribute('fill','transparent');rect.setAttribute('pointer-events','all');
    rect.setAttribute('aria-hidden','true');rect.classList.add('view-hit-area');
    group.prepend(rect);
  }
}
async function renderPaper(epoch=++renderEpoch,fitting=false){if(!doc||!edit)return;const currentSheet=sheetId;const result=await api(url()+'/render',{edit,sheet:currentSheet});if(epoch!==renderEpoch||sheetId!==currentSheet)return;tableMetrics=result.table_metrics||{};const parsed=new DOMParser().parseFromString(result.svg,'image/svg+xml');$('paper-container').replaceChildren(document.importNode(parsed.documentElement,true));installViewHitAreas();sheetSize=parsed.documentElement.getAttribute('viewBox').split(' ').slice(2).map(Number);$('empty').hidden=true;highlight();showIssues(result.issues);if(fitting)fit();else paintTransform();if(findItem()?.key==='tables')properties();if(pick)showSnapPoints(result.anchors);}
function showIssues(issues){$('issues').replaceChildren();for(const i of issues){const b=button($('issues'),`${i.severity==='error'?'Required':'Review'} · ${i.message}`,()=>{const found=findItem(i.item);if(found){sheetId=found.value.sheet||found.value.id;selected(i.item);requestRender();}},'issue '+i.severity);if(!i.item)b.disabled=false;}if(!issues.length)$('issues').append(el('p','Drawing checks: no current issues. Engineering release remains a human decision.','muted'));if(issues.some(i=>i.severity==='error'))document.querySelector('.drawing-checks').open=true;}
function uid(prefix){return prefix+'-'+crypto.randomUUID().replaceAll('-','').slice(0,12);}
async function list(){const rows=await api(base());$('documents').replaceChildren();for(const row of rows){const b=button($('documents'),row.metadata?.number||row.id,async()=>{if(dirty&&!confirm('Discard unsaved drawing edits?'))return;await open(row.id);},'tree-button'+(doc?.id===row.id?' active':''));b.append(el('small',`${row.kind||''} · ${row.status}${row.source_current?'':' · source changed'}`));}if(!rows.length)$('documents').append(el('p','No drawings yet.','muted'));}
async function open(id){if(busy)return;renderEpoch++;doc=await api(`${base()}/${id}`);window.history.replaceState(null,'',`/drawing.html?project=${projectId}&drawing=${doc.id}`);edit=clone(doc.edit);tableMetrics=doc.table_metrics||{};sheetId=edit.sheets[0].id;selection=null;dirty=false;history=[];future=[];controls();tree();properties();await list();requestRender(true);message(doc.source_current?'Drawing opened. Select an item or add a dimension.':'Source changed. Saved drawing retained; Update from Manifold to regenerate.');$('recovery').hidden=true;try{const recovery=JSON.parse(localStorage.getItem(recoveryKey())||'null');if(recovery){$('recovery').hidden=false;$('recovery').replaceChildren(el('span',recovery.revision===doc.revision?'Unsaved drawing edits can be recovered.':'Recovery belongs to an older saved version. Review carefully before saving.'));button($('recovery'),'Recover edits',()=>{edit=recovery.edit;sheetId=edit.sheets[0].id;dirty=true;controls();tree();properties();requestRender(true);$('recovery').hidden=true;});button($('recovery'),'Discard recovery',()=>{localStorage.removeItem(recoveryKey());$('recovery').hidden=true;});}}catch{} }
async function save(){if(!doc||doc.status==='Released')return;if(busy)throw Error('Wait for the current drawing operation');busy=true;controls();message('Saving drawing…');try{doc=await api(url()+'/save',{expected_revision:doc.revision,edit});edit=clone(doc.edit);dirty=false;remember();controls();await list();}finally{busy=false;controls();tree();properties();}message('Drawing saved to Project.');return doc;}
async function runJob(start,keepBusy=false){busy=true;controls();try{jobId=(await start()).job_id;$('cancel-job').hidden=false;for(;;){const state=await api(base()+'/jobs/'+jobId);message(state.message);if(state.state==='completed')return state.result;if(['failed','cancelled'].includes(state.state))throw Error(state.message);await new Promise(resolve=>setTimeout(resolve,500));}}finally{if(!keepBusy)busy=false;jobId=null;$('cancel-job').hidden=true;controls();}}
$('cancel-job').onclick=()=>jobId&&api(base()+'/jobs/'+jobId+'/cancel',{}).catch(fail);
async function createModal(){const templates=await api('/api/drawings/templates');modal('Create Drawing',body=>{body.append(el('p','Use this project’s saved, exact manifold build. Customer and manufacturing drawings share the same editor.'));let kind='customer',template='pmc-customer',number=project.design.name;field(body,'Drawing template',template,v=>{template=v;kind=templates.find(t=>t.id===v).kind;},'text',templates.map(t=>[t.id,t.name]));field(body,'Drawing number',number,v=>number=v);const row=el('div',null,'row');button(row,'Create engineering drawing',async()=>{if(dirty&&!confirm('Discard current unsaved drawing edits?'))return;$('modal').close();project=await api('/api/projects/'+projectId);const result=await runJob(()=>api(base(),{kind,number,template_id:template,expected_source:project.revision}));await open(result.drawing_id);},'primary');button(row,'Open source Manifold',()=>location.href='/?project='+projectId);body.append(row);});}
function deleteSelected(){const found=findItem();if(!found)return;changed(()=>{const {key,value}=found;if(key==='sheets'){if(edit.sheets.length===1)throw Error('A drawing must retain one sheet');if(['views','annotations','tables','schematics'].some(k=>edit[k].some(i=>i.sheet===value.id)))throw Error('Move or delete this sheet’s objects before deleting the sheet');edit.sheets=edit.sheets.filter(s=>s.id!==value.id);sheetId=edit.sheets[0].id;}else{if(key==='annotations'&&value.automatic)edit.suppressed.push(value.id);if(key==='views'){for(const a of edit.annotations.filter(a=>a.view===value.id&&a.automatic))edit.suppressed.push(a.id);edit.annotations=edit.annotations.filter(a=>a.view!==value.id);}edit[key]=edit[key].filter(i=>i.id!==value.id);}selection=null;});}
function anchorOptions(){return Object.entries(doc.anchors).map(([k,a])=>[k,a.label+' · '+k]);}
function annotationModal(kind){modal(kind==='dimension'?'Add engineering dimension':'Add leader / label',body=>{const viewOptions=edit.views.filter(v=>v.sheet===sheetId).map(v=>[v.id,v.title||v.id]);if(!viewOptions.length){body.append(el('p','Add a view to this sheet first.'));return;}let view=viewOptions[0][0],measure='x',a='B:000',b='B:100',text='',label=false;field(body,'Drawing view',view,v=>view=v,'text',viewOptions);if(kind==='dimension')field(body,'Measurement',measure,v=>measure=v,'text',['x','y','aligned','diameter','radius','depth','angle']);else{field(body,'Label text',text,v=>text=v);field(body,'Label without leader',label,v=>label=v,'checkbox');}field(body,'First anchor',a,v=>a=v,'text',anchorOptions());if(kind==='dimension')field(body,'Second anchor (linear dimensions)',b,v=>b=v,'text',anchorOptions());body.append(el('p','Values come from the source model. Select source anchors here, or pick them directly on the drawing.'));const row=el('div',null,'row');const add=(keys)=>{const value={id:uid(kind),kind:kind==='dimension'?'dimension':label?'label':'leader',sheet:sheetId,view,anchors:keys,measure,position:kind==='dimension'?[12,16]:[12,-12],text,precision:2,height:3,visible:true,automatic:false};changed(()=>{edit.annotations.push(value);selection=value.id;});};button(row,'Add',()=>{add(kind==='dimension'&&['x','y','aligned'].includes(measure)?[a,b]:[a]);$('modal').close();},'primary');button(row,'Pick anchors on paper',()=>{pick={view,count:kind==='dimension'&&['x','y','aligned'].includes(measure)?2:1,keys:[],add};$('modal').close();message('Pick the highlighted engineering anchors on this view. Escape cancels.');requestRender();});body.append(row);});}
function showSnapPoints(anchors){const root=$('paper-container svg');if(!root)return;for(const p of anchors.filter(a=>a.view===pick.view)){const c=document.createElementNS('http://www.w3.org/2000/svg','circle');for(const [k,v]of Object.entries({cx:p.x,cy:p.y,r:1.6,class:'snap-point'}))c.setAttribute(k,v);const title=document.createElementNS(c.namespaceURI,'title');title.textContent=p.label;c.append(title);c.onpointerdown=e=>{e.stopPropagation();pick.keys.push(p.key);if(pick.keys.length===pick.count){const done=pick;pick=null;done.add(done.keys);message('Associative annotation added.');}else message('Pick the second engineering anchor.');};root.append(c);}}
function bindModal(item){modal('Rebind engineering reference',body=>{let a=item.anchors[0]||'B:000',b=item.anchors[1]||'B:100';field(body,'First anchor',a,v=>a=v,'text',anchorOptions());if(item.anchors.length===2)field(body,'Second anchor',b,v=>b=v,'text',anchorOptions());button(body,'Confirm source association',async()=>{const rebound=clone(edit);rebound.annotations.find(v=>v.id===item.id).anchors=item.anchors.length===2?[a,b]:[a];doc=await api(url()+'/rebind',{expected_revision:doc.revision,edit:rebound,annotation:item.id});edit=clone(doc.edit);dirty=false;remember();$('modal').close();controls();properties();requestRender();},'primary');});}
function viewModal(){modal('Add view or section',body=>{let projection='front',scale=.5,section=20;field(body,'Projection',projection,v=>projection=v,'text',['front','back','left','right','top','bottom','iso','section-x','section-y','section-z']);field(body,'Scale',scale,v=>scale=v,'number');field(body,'Section coordinate (mm)',section,v=>section=v,'number');body.append(el('p','Adding a new projection or changing a section requires regeneration from the same saved engineering build.'));button(body,'Add view',()=>{changed(()=>{const value={id:uid('view'),sheet:sheetId,projection,position:[40,45],scale,hidden:projection.startsWith('section-'),centerlines:true,visible:true,title:projection.toUpperCase(),section_at:projection.startsWith('section-')?section:null};edit.views.push(value);selection=value.id;});$('modal').close();message('View added. Update from Manifold to compute a new projection if needed.');},'primary');});}
function tableModal(){modal('Add engineering table',body=>{let kind='porting',start=0,count=20,displayRows=null;field(body,'Table type',kind,v=>kind=v,'text',['porting','machining']);field(body,'Start source group',start,v=>start=v,'number');field(body,'Source groups on this table',count,v=>count=v,'number');field(body,'Displayed rows (blank = fit content)','',v=>displayRows=v.trim()===''?null:Number(v));button(body,'Add table',()=>{changed(()=>{const value={id:uid('table'),sheet:sheetId,kind,position:[25,35],width:300,row_height:8,height:2.8,start,count,display_rows:displayRows,order:[],remarks:{},visible:true};edit.tables.push(value);selection=value.id;});$('modal').close();},'primary');});}
function schematicModal(){modal('Add project schematic',body=>{if(!doc.assets.length){body.append(el('p','No schematic belongs to this source. Attach it in Manifold Studio, save/build, then update the drawing.'));return;}let asset=doc.assets[0].sha256,page=0;field(body,'Project schematic',asset,v=>asset=v,'text',doc.assets.map(a=>[a.sha256,a.name]));field(body,'Page (zero based)',page,v=>page=v,'number');button(body,'Add schematic',()=>{changed(()=>{const value={id:uid('schematic'),sheet:sheetId,asset,page,position:[25,35],width:130,height:100,crop:[0,0,1,1],visible:true};edit.schematics.push(value);selection=value.id;});$('modal').close();},'primary');});}
async function update(){
  if(busy||!doc||doc.status!=='Draft')return;
  const sourceId=doc.id,sourceRevision=doc.revision,sourceUrl=url(),sourceSheet=sheetId;
  const sourceEdit=clone(edit),sourceSignature=JSON.stringify(sourceEdit);
  busy=true;controls();
  try{
    project=await api('/api/projects/'+projectId);
    const result=await runJob(()=>api(sourceUrl+'/update',{expected_revision:sourceRevision,expected_source:project.revision,edit:sourceEdit}),true);
    const preview=await api(sourceUrl+'/preview-update',{candidate_id:result.candidate_id,expected_revision:sourceRevision,sheet:result.document.edit.sheets.find(s=>s.id===sourceSheet)?.id||result.document.edit.sheets[0].id});
    if(doc.id!==sourceId||doc.revision!==sourceRevision||JSON.stringify(edit)!==sourceSignature)throw Error('Drawing changed while preparing source update. Local edits were retained; review again.');
    modal('Review source update',body=>{
      const previewNode=el('div',null,'update-preview');
      previewNode.append(document.importNode(new DOMParser().parseFromString(preview.svg,'image/svg+xml').documentElement,true));
      body.append(previewNode);
      body.append(el('p',`${result.added.length} new annotations. ${Object.keys(result.broken).length} broken references require rebinding or deletion. Existing view positions, scales and independent notes are retained.`));
      for(const [id,reason] of Object.entries(result.broken))body.append(el('p',id+': '+reason));
      const row=el('div',null,'row');
      button(row,'Apply update',async()=>{
        if(doc.id!==sourceId||doc.revision!==sourceRevision||JSON.stringify(edit)!==sourceSignature)throw Error('Drawing changed since this update was prepared. Local edits were retained; start a new source update.');
        busy=true;controls();
        try{
          doc=await api(sourceUrl+'/apply-update',{candidate_id:result.candidate_id,expected_revision:sourceRevision});
          edit=clone(doc.edit);dirty=false;history=[];future=[];remember();$('modal').close();tree();properties();requestRender();
          message('Drawing updated. Resolve any broken references before release.');
        }finally{busy=false;controls();}
      },'primary');
      button(row,'Keep existing drawing',()=>{if(!busy)$('modal').close();});
      body.append(row);
    });
  }finally{busy=false;controls();}
}
function revisionModal(){modal('Create next revision',body=>{let label='',note='';field(body,'New revision label',label,v=>label=v);field(body,'Revision description',note,v=>note=v,'textarea');button(body,'Create draft revision',async()=>{if(dirty)await save();doc=await api(url()+'/revision',{expected_revision:doc.revision,revision:label,note});edit=clone(doc.edit);dirty=false;history=[];future=[];$('modal').close();controls();properties();requestRender();await list();message('New draft revision created. Previous issued PDFs remain unchanged.');},'primary');});}
async function releaseModal(){if(dirty)await save();doc=await api(url());modal('Release drawing revision',body=>{body.append(el('p','Release freezes this revision and its PDF. Engineering validation and manufacturing readiness retain their original results.'));let by='',exceptions={};field(body,'Released by',by,v=>by=v);for(const i of doc.issues){if(i.severity==='error')body.append(el('p','BLOCKED: '+i.message));else field(body,'Decision: '+i.message,'',v=>{if(v.trim())exceptions[i.code]=v;else delete exceptions[i.code];},'textarea');}button(body,'Release immutable PDF',async()=>{doc=await api(url()+'/release',{expected_revision:doc.revision,released_by:by,exceptions});edit=clone(doc.edit);dirty=false;remember();$('modal').close();controls();properties();requestRender();await list();message('Drawing revision released. Create a new revision for further edits.');},'primary');});}
async function showHistory(){const [rows,saves]=await Promise.all([api(url()+'/revisions'),api(url()+'/history')]);modal('Drawing revision and save history',body=>{body.append(el('h3','Released revisions'));if(!rows.length)body.append(el('p','No released revisions yet.'));for(const row of rows){const entry=el('div',null,'history-entry');entry.append(el('strong','Revision '+row.revision),el('p',row.release.date+' · '+row.release.by));button(entry,'Download immutable PDF',()=>download(url()+'/revisions/'+row.id+'/pdf','released-revision.pdf'));body.append(entry);}body.append(el('h3','Recent saved states'));for(const row of saves){const entry=el('div',null,'history-entry');entry.append(el('strong',row.status+' · Rev '+row.revision),el('p',row.updated_at+' · build '+row.source_build.slice(0,12)));button(entry,'Review saved PDF',()=>download(url()+'/history/'+row.id+'/pdf','saved-drawing.pdf'));button(entry,'Copy this state as a draft',async()=>{if(dirty&&!confirm('Discard current unsaved drawing edits?'))return;const copy=await api(url()+'/history/'+row.id+'/duplicate',{});$('modal').close();await open(copy.id);});body.append(entry);}});}
async function download(path,name){const response=await fetch(path);if(!response.ok){const data=await response.json().catch(()=>({}));throw Error(data.detail||'PDF export failed. The saved drawing is retained.');}const objectUrl=URL.createObjectURL(await response.blob());const a=el('a');a.href=objectUrl;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(objectUrl),30000);message('PDF exported from the saved drawing.');}
const handlers={create:createModal,save,dimension:()=>annotationModal('dimension'),leader:()=>annotationModal('leader'),view:viewModal,table:tableModal,schematic:schematicModal,update,revision:revisionModal,release:releaseModal,history:showHistory,metadata:()=>selected(null),duplicate:async()=>{if(dirty)await save();const copy=await api(url()+'/duplicate',{expected_revision:doc.revision});await open(copy.id);},pdf:async()=>{if(dirty)await save();message('Preparing engineering PDF…');await download(url()+'/pdf','drawing.pdf');},text:()=>changed(()=>{const value={id:uid('note'),kind:'text',sheet:sheetId,view:null,anchors:[],measure:'x',position:[30,40],text:'New note',precision:2,height:3,visible:true,automatic:false};edit.annotations.push(value);selection=value.id;}),'sheet-add':()=>changed(()=>{const s={id:uid('sheet'),title:'Additional sheet',size:'A2',landscape:true};edit.sheets.push(s);sheetId=s.id;selection=s.id;})};for(const [id,fn]of Object.entries(handlers))$(id).onclick=()=>Promise.resolve().then(fn).catch(fail);
function undo(redo=false){const from=redo?future:history,to=redo?history:future;if(busy||doc?.status!=='Draft'||!from.length)return;to.push(clone(edit));edit=from.pop();if(!edit.sheets.some(s=>s.id===sheetId))sheetId=edit.sheets[0].id;dirty=true;remember();controls();tree();properties();requestRender();}
$('undo').onclick=()=>undo();$('redo').onclick=()=>undo(true);$('fit').onclick=fit;$('zoom-in').onclick=()=>{zoom=Math.min(8,zoom*1.2);paintTransform();};$('zoom-out').onclick=()=>{zoom=Math.max(.15,zoom/1.2);paintTransform();};
const viewport=$('paper-viewport');viewport.addEventListener('wheel',e=>{if(!doc)return;e.preventDefault();const r=viewport.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,old=zoom;zoom=Math.min(8,Math.max(.15,zoom*(e.deltaY<0?1.12:1/1.12)));pan=[x-(x-pan[0])*zoom/old,y-(y-pan[1])*zoom/old];paintTransform();},{passive:false});
viewport.onpointerdown=e=>{if(pick)return;const group=e.target.closest('g[data-item]'),found=group&&findItem(group.dataset.item);if(found&&found.key!=='sheets'&&doc?.status==='Draft'&&!busy&&e.button===0){selected(found.value.id);drag={mode:'item',start:[e.clientX,e.clientY],position:clone(found.value.position),item:found.value,before:clone(edit)};}else drag={mode:'pan',start:[e.clientX,e.clientY],pan:[...pan]};viewport.setPointerCapture(e.pointerId);};
viewport.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.start[0],dy=e.clientY-drag.start[1];if(drag.mode==='pan'){pan=[drag.pan[0]+dx,drag.pan[1]+dy];paintTransform();return;}const x=dx/zoom,y=dy/zoom;const ids=[drag.item.id,...edit.annotations.filter(a=>a.view===drag.item.id).map(a=>a.id)];for(const id of ids)for(const g of $('paper-container').querySelectorAll(`[data-item="${CSS.escape(id)}"]`))g.setAttribute('transform',`translate(${x},${y})`);};
viewport.onpointercancel=()=>{drag=null;requestRender();};
viewport.onpointerup=e=>{if(!drag)return;const current=drag;drag=null;if(current.mode==='item'){const dx=(e.clientX-current.start[0])/zoom,dy=(e.clientY-current.start[1])/zoom;if(Math.abs(dx)+Math.abs(dy)>.2){history.push(current.before);future=[];current.item.position=[Math.round((current.position[0]+dx)*10)/10,Math.round((current.position[1]+dy)*10)/10];dirty=true;remember();controls();properties();requestRender();}}};
window.addEventListener('keydown',e=>{if(e.defaultPrevented||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)||$('modal').open)return;if(e.key==='Escape'&&pick){e.preventDefault();pick=null;requestRender();return;}if(e.key==='Delete'){e.preventDefault();deleteSelected();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save().catch(fail);}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
setInterval(async()=>{if(!doc||busy||document.hidden)return;try{const current=await api(url());if(current.revision!==doc.revision){message('Drawing changed in another window. Your local edits are retained; reopen before saving.',true);}doc.source_current=current.source_current;controls();}catch(e){fail(e);}},8000);
async function init(){if(!/^[0-9a-f]{32}$/.test(projectId||''))throw Error('Open a saved Project and select Drawings.');project=await api('/api/projects/'+projectId);$('project-title').textContent=project.design.name;$('back').href='/?project='+projectId;controls();await list();const requested=new URLSearchParams(location.search).get('drawing');if(requested)await open(requested);else message(project.build?'Choose an existing drawing or Create Drawing.':'Validate the source Manifold before creating a drawing.');}
init().catch(fail);
