import {isCavity} from './definition-role.js';
import {profileEditor} from './profile.js';

export function libraryUI(ctx,{open,insert,onCustomSaved=()=>{}}){
  const {$,element,field,action,api,post}=ctx,content=$('workflow-content');
  const guard=fn=>async()=>{try{await fn();$('workflow-error').textContent='';}catch(e){$('workflow-error').textContent=e.message;}};
  let generation=0;
  const blank=()=>({id:'custom_pending',label:'Custom cavity',family:'Custom',unit_system:ctx.get().project_context||'metric',manufacturer:'',thread_note:'',
    stages:[{start:0,end:20,diameter:20}],zones:[{id:'port1',start:10,end:18,diameter:18,offset_u:0,offset_v:0,clip_to_cut:true}],
    clearance_diameter:24,clearance_height:20,cutting_primitives:[],boundaries:[],machining:[],usable:true,unusable_reason:'',active:true,kind:'cavity'});

  function validationErrors(definition){
    const errors=[];
    definition.stages.forEach((row,index)=>{
      if(!(row.end>row.start))errors.push(`Stage ${index+1}: end depth must be greater than start depth.`);
      if(index===0&&Math.abs(row.start)>1e-6)errors.push('Stage 1 must start at depth 0.');
      if(index&&Math.abs(row.start-definition.stages[index-1].end)>1e-6)errors.push(`Stage ${index+1}: start depth must equal the previous end depth.`);
      if(index&&row.diameter>definition.stages[index-1].diameter)errors.push(`Stage ${index+1}: diameter cannot increase with depth.`);
    });
    const ids=new Set();
    definition.zones.forEach((row,index)=>{
      if(ids.has(row.id))errors.push(`Interface ${index+1}: duplicate interface ID.`);ids.add(row.id);
      if(!(row.end>row.start))errors.push(`Interface ${index+1}: end depth must be greater than start depth.`);
      if(!definition.cutting_primitives.length&&!definition.stages.some(stage=>stage.start<=row.start&&row.end<=stage.end&&row.diameter<=stage.diameter))errors.push(`Interface ${index+1}: hydraulic window must lie inside a machining stage.`);
    });
    definition.cutting_primitives.forEach((row,index)=>{if(!(row.end>row.start))errors.push(`Cutting primitive ${index+1}: end depth must be greater than start depth.`);if(row.kind==='annulus'&&!(row.inner_diameter<row.diameter))errors.push(`Cutting primitive ${index+1}: inner diameter must be smaller than outer diameter.`);});
    const outer=Math.max(0,...definition.stages.map(row=>row.diameter),...definition.cutting_primitives.map(row=>2*Math.hypot(row.offset_u||0,row.offset_v||0)+Math.max(row.diameter||0,row.end_diameter||0)));
    if(definition.clearance_diameter<outer)errors.push(`Clearance diameter must cover the ${outer.toFixed(2)} mm outer profile.`);
    definition.boundaries.forEach((row,index)=>{if(row.circle&&!(row.circle[2]>0))errors.push(`Boundary ${index+1}: circle radius must be positive.`);if(!row.circle&&(row.points||[]).length<3)errors.push(`Boundary ${index+1}: polygon requires at least three points.`);});
    return errors;
  }

  function editCustom(source=null,backOptions={}){
    ++generation;const definition=structuredClone(source||blank());definition.id='custom_pending';definition.kind='cavity';definition.active=true;definition.usable=true;definition.unusable_reason='';
    const render=()=>{
      open(source?'Duplicate as Custom Cavity':'Create Custom Cavity');content.append(element('p','Saving creates a new stable SQLite cavity ID. The source/master definition and existing projects are not changed.'));
      const edit=(parent,label,value,set,options=null,numeric=false)=>field(parent,label,value,v=>{set(v);render();},options,numeric);
      const basics=element('section',null,'editor-grid');content.append(basics);
      edit(basics,'Display name',definition.label,v=>definition.label=v);edit(basics,'Engineering units',definition.unit_system,v=>definition.unit_system=v,{metric:'Metric',inch:'Inch',custom:'Custom'});edit(basics,'Family / type',definition.family,v=>definition.family=v);edit(basics,'Manufacturer',definition.manufacturer,v=>definition.manufacturer=v);edit(basics,'Thread / note',definition.thread_note,v=>definition.thread_note=v);edit(basics,'Clearance diameter / mm',definition.clearance_diameter,v=>definition.clearance_diameter=v,null,true);edit(basics,'Clearance height / mm',definition.clearance_height,v=>definition.clearance_height=v,null,true);for(const message of validationErrors(definition).filter(value=>value.startsWith('Clearance diameter')))basics.append(element('p',message,'error'));

      const rowActions=(parent,rows,index,make)=>{const bar=element('div',null,'action-row');parent.append(bar);action(bar,'Duplicate',()=>{rows.splice(index+1,0,structuredClone(rows[index]));render();});action(bar,'Move up',()=>{if(index){[rows[index-1],rows[index]]=[rows[index],rows[index-1]];render();}});action(bar,'Move down',()=>{if(index<rows.length-1){[rows[index+1],rows[index]]=[rows[index],rows[index+1]];render();}});action(bar,'Delete',()=>{rows.splice(index,1);if(!rows.length&&make&&rows===definition.stages)rows.push(make());render();});};
      const section=(title,rows,make,build)=>{const singular={ 'Machining stages':'Machining stage','Cutting primitives':'Cutting primitive','Hydraulic interfaces':'Hydraulic interface','Supported boundaries':'Supported boundary','Machining operations':'Machining operation'}[title]||title;const box=element('section',null,'library-card');box.append(element('h3',`${title} · ${rows.length}`));content.append(box);rows.forEach((item,index)=>{const row=element('section',null,'port-row');row.append(element('h4',`${singular} ${index+1}`));box.append(row);build(row,item,index);rowActions(row,rows,index,make);});action(box,`+ Add ${singular.toLowerCase()}`,()=>{rows.push(make());render();});};

      section('Machining stages',definition.stages,()=>{const previous=definition.stages.at(-1);return {start:previous?.end||0,end:(previous?.end||0)+10,diameter:previous?.diameter||10};},(row,item,index)=>{const type=field(row,'Type','Cylinder',()=>{},{cylinder:'Cylinder'});type.disabled=true;edit(row,'Start depth / mm',item.start,v=>item.start=v,null,true);edit(row,'End depth / mm',item.end,v=>item.end=v,null,true);edit(row,'Diameter / mm',item.diameter,v=>item.diameter=v,null,true);for(const message of validationErrors(definition).filter(value=>value.startsWith(`Stage ${index+1}:`)))row.append(element('p',message,'error'));});
      section('Cutting primitives',definition.cutting_primitives,()=>({kind:'cylinder',start:0,end:10,diameter:10,end_diameter:10,inner_diameter:0,offset_u:0,offset_v:0,source_ref:'Custom'}),(row,item,index)=>{edit(row,'Type',item.kind,v=>item.kind=v,{cylinder:'Cylinder',cone:'Cone',annulus:'Annulus'});edit(row,'Start depth / mm',item.start,v=>item.start=v,null,true);edit(row,'End depth / mm',item.end,v=>item.end=v,null,true);edit(row,'Diameter / mm',item.diameter,v=>item.diameter=v,null,true);if(item.kind==='cone')edit(row,'End diameter / mm',item.end_diameter,v=>item.end_diameter=v,null,true);if(item.kind==='annulus')edit(row,'Inner diameter / mm',item.inner_diameter,v=>item.inner_diameter=v,null,true);edit(row,'Offset U / mm',item.offset_u||0,v=>item.offset_u=v,null,true);edit(row,'Offset V / mm',item.offset_v||0,v=>item.offset_v=v,null,true);for(const message of validationErrors(definition).filter(value=>value.startsWith(`Cutting primitive ${index+1}:`)))row.append(element('p',message,'error'));});
      section('Hydraulic interfaces',definition.zones,()=>({id:`port${definition.zones.length+1}`,start:0,end:5,diameter:5,offset_u:0,offset_v:0,clip_to_cut:true}),(row,item,index)=>{edit(row,'Interface ID',item.id,v=>item.id=v);edit(row,'Start depth / mm',item.start,v=>item.start=v,null,true);edit(row,'End depth / mm',item.end,v=>item.end=v,null,true);edit(row,'Hydraulic diameter / mm',item.diameter,v=>item.diameter=v,null,true);edit(row,'Offset U / mm',item.offset_u||0,v=>item.offset_u=v,null,true);edit(row,'Offset V / mm',item.offset_v||0,v=>item.offset_v=v,null,true);edit(row,'Clip to machining volume',String(!!item.clip_to_cut),v=>item.clip_to_cut=v==='true',{true:'Yes',false:'No'});for(const message of validationErrors(definition).filter(value=>value.startsWith(`Interface ${index+1}:`)))row.append(element('p',message,'error'));});
      section('Supported boundaries',definition.boundaries,()=>({category:'mounting-footprint',circle:[0,0,10],points:[],height:0}),(row,item,index)=>{const type=item.circle?'circle':'polygon';edit(row,'Boundary type',type,v=>{if(v==='circle'){item.circle=[0,0,10];item.points=[];}else{item.circle=null;item.points=[[0,0],[10,0],[0,10]];}},{circle:'Circle',polygon:'Polygon'});edit(row,'Category',item.category,v=>item.category=v,{'mounting-footprint':'Mounting footprint','external-body':'External body',service:'Service',tool:'Tool'});edit(row,'Height / mm',item.height||0,v=>item.height=v,null,true);if(item.circle){for(const [i,label]of ['Center U / mm','Center V / mm','Radius / mm'].entries())edit(row,label,item.circle[i],v=>item.circle[i]=v,null,true);}else{for(const [i,point]of (item.points||[]).entries()){const pointRow=element('div',null,'field-row');row.append(pointRow);edit(pointRow,`Point ${i+1} U`,point[0],v=>point[0]=v,null,true);edit(pointRow,`Point ${i+1} V`,point[1],v=>point[1]=v,null,true);action(pointRow,'Delete point',()=>{item.points.splice(i,1);render();});}action(row,'+ Add polygon point',()=>{item.points.push([0,0]);render();});}for(const message of validationErrors(definition).filter(value=>value.startsWith(`Boundary ${index+1}:`)))row.append(element('p',message,'error'));});
      section('Machining operations',definition.machining,()=>({operation:'',tool:'',depth:null,note:'',source:''}),(row,item)=>{edit(row,'Operation',item.operation||'',v=>item.operation=v);edit(row,'Tool / cutter',item.tool||'',v=>item.tool=v);edit(row,'Depth / mm',item.depth??'',v=>item.depth=v===''?null:v,null,true);edit(row,'Note',item.note||'',v=>item.note=v);edit(row,'Source',item.source||'',v=>item.source=v);});

      const errors=validationErrors(definition);if(errors.length){const box=element('section',null,'error');box.append(element('strong','Correct these fields before saving:'));for(const value of errors)box.append(element('p',value));content.append(box);}profileEditor(ctx,content,definition,{editable:false});
      const advanced=element('details');advanced.append(element('summary','Advanced · Raw engineering JSON (import/debug only)'));content.append(advanced);for(const [label,key]of [['Machining stages','stages'],['Cutting primitives','cutting_primitives'],['Hydraulic interfaces','zones'],['Supported boundaries','boundaries'],['Machining operations','machining']]){const wrap=element('label',label+' JSON','field'),input=element('textarea');input.value=JSON.stringify(definition[key],null,2);input.spellcheck=false;input.onchange=()=>{try{const value=JSON.parse(input.value);if(!Array.isArray(value))throw Error('Expected a JSON array');definition[key]=value;render();}catch(error){$('workflow-error').textContent=`${label}: ${error.message}`;}};wrap.append(input);advanced.append(wrap);}
      const buttons=element('div',null,'action-row');content.append(buttons);const save=action(buttons,'Save New Custom Cavity',guard(async()=>{const invalid=validationErrors(definition);if(invalid.length)throw Error(invalid[0]);const saved=await post('/api/catalog/custom-cavity',{definition});onCustomSaved(saved);open('Custom cavity saved');content.append(element('h3',saved.label),element('p',`${saved.id}\n${saved.unit_system.toUpperCase()} · ${saved.family||'Custom'}\nThe new record is active in the SQLite Engineering Library and can replace a placed cavity.`));action(content,'Place this cavity',()=>insert(saved));action(content,'Back to Engineering Library',()=>library(backOptions));}));save.classList.add('primary');save.disabled=!!errors.length;action(buttons,'Cancel',()=>library(backOptions));
    };render();
  }

  function viewDefinition(definition,options={}){++generation;open('Cavity Definition · '+definition.label);content.append(element('p',`${definition.id.startsWith('custom_')||definition.id.startsWith('legacy_')?'CUSTOM / LOCAL':'PMC MASTER'} · ${definition.unit_system.toUpperCase()} · ${definition.family||'Family unspecified'}\nEngineering reference: ${definition.id}`));profileEditor(ctx,content,definition,{editable:false,interfaceNames:options.interfaceNames||{}});const row=element('div',null,'action-row');content.append(row);action(row,options.actionLabel||'Place Cavity',()=>{(options.onSelect||insert)(definition);});action(row,'Duplicate as Custom',()=>editCustom(definition,options));action(row,'Back to Engineering Library',()=>library(options));}

  async function library(options={}){
    const openToken=++generation;open(options.title||'Engineering Library · SQLite');content.append(element('p','Search the runtime engineering database. A selected cavity is referenced by ID; its full definition is loaded for this session and is not embedded in the project.'));const createRow=element('div',null,'action-row');content.append(createRow);action(createRow,'Create Custom Cavity',()=>editCustom(null,options));const filters=element('div',null,'editor-grid'),list=element('div',null,'library-list'),pager=element('div',null,'action-row');content.append(filters,list,pager);
    const query={q:'',unit:ctx.get().project_context||'',kind:'cavity',family:'',manufacturer:'',thread:'',status:'all',scope:'all',offset:0,limit:30};let timer,requestGeneration=0;
    const load=async()=>{const request=++requestGeneration;list.replaceChildren(element('p','Loading SQLite engineering data…'));pager.replaceChildren();try{const result=await api('/api/catalog?'+new URLSearchParams(query));if(openToken!==generation||request!==requestGeneration)return;list.replaceChildren(element('p',`${result.total.toLocaleString()} matching cavities`));for(const row of result.items){const card=element('section',null,'library-card'),custom=row.id.startsWith('custom_')||row.id.startsWith('legacy_');list.append(card);card.append(element('h3',row.name),element('p',`${custom?'CUSTOM / LOCAL':'PMC MASTER'} · ${row.manufacturer||'Manufacturer unspecified'} · ${row.family||'Family unspecified'} · ${row.unit_system.toUpperCase()}\n${row.thread_spec||'No thread specification'}\nEngineering reference: ${row.id}`));if(!row.usable)card.append(element('p','Unavailable: '+row.unusable_reason,'error'));action(card,'View Definition',guard(async()=>{const definition=await api('/api/catalog/definition?'+new URLSearchParams({id:row.id}));if(!isCavity(definition))throw Error('Selected record is not a cavity.');viewDefinition(definition,options);}));if(row.usable)action(card,options.actionLabel||'Place Cavity',guard(async()=>{const definition=await api('/api/catalog/definition?'+new URLSearchParams({id:row.id}));if(!isCavity(definition))throw Error('Selected record is not a cavity.');(options.onSelect||insert)(definition);}));}if(query.offset>0)action(pager,'Previous page',()=>{query.offset=Math.max(0,query.offset-query.limit);load();});pager.append(element('span',result.total?`${query.offset+1}–${Math.min(query.offset+query.limit,result.total)} / ${result.total}`:'0 results'));if(query.offset+query.limit<result.total)action(pager,'Next page',()=>{query.offset+=query.limit;load();});$('workflow-error').textContent='';}catch(e){if(openToken!==generation||request!==requestGeneration)return;list.replaceChildren(element('p','Engineering Library failed to load: '+e.message,'error'));$('workflow-error').textContent=e.message;}};
    const update=(key,value)=>{query[key]=value;query.offset=0;clearTimeout(timer);timer=setTimeout(load,180);};const search=field(filters,'Search cavity',query.q,v=>update('q',v));search.oninput=()=>update('q',search.value);field(filters,'Engineering units',query.unit,v=>update('unit',v),{'':'All units',metric:'Metric',inch:'Inch',custom:'Custom'});field(filters,'Family / type',query.family,v=>update('family',v));field(filters,'Manufacturer',query.manufacturer,v=>update('manufacturer',v));field(filters,'Thread',query.thread,v=>update('thread',v));field(filters,'Library scope',query.scope,v=>update('scope',v),{all:'Master and custom',master:'PMC master',custom:'Custom / local'});field(filters,'Engineering availability',query.status,v=>update('status',v),{all:'Usable and unavailable',usable:'Usable only',unavailable:'Unavailable only'});content.append(element('p','External-port definitions are selected from Add External Port. Cartridge assignments are chosen on a placed cavity and validated by the explicit database relationship.'));await load();
  }
  library.viewDefinition=(definition,options={})=>viewDefinition(definition,options);library.duplicateAsCustom=(definition,options={})=>editCustom(definition,options);return library;
}
