import {isCavity,isPort} from './definition-role.js';
import {profileEditor} from './profile.js';
import {engineeringFactsUI} from './engineering-facts-ui.js';
import {relationKnowledgeUI} from './relation-knowledge-ui.js';
import {libraryBrowser,recordMore} from './library-browser.js';
import {engineeringName,engineeringText,unitLabel,availability,machiningRecipe} from './engineering-labels.js';

export function libraryUI(ctx,{open,insert,onCustomSaved=()=>{},scrollContainer=()=>ctx.$('workflow-dialog')}){
  const {$,element,field,action,api,post}=ctx,content=$('workflow-content');
  const guard=fn=>async()=>{try{await fn();$('workflow-error').textContent='';}catch(e){$('workflow-error').textContent=engineeringText(e.message);}};
  let generation=0;
  function placement(parent,label,callback){const button=action(parent,label,callback);if(!ctx.get()){button.disabled=true;button.title='Open or create a manifold before placing a feature.';}return button;}
  function selectOrPlace(parent,label,callback,options){return options.selectionMode==='cavity'||options.selectionMode==='external-port'?action(parent,label,callback):placement(parent,label,callback);}
  const blank=(kind='cavity')=>({id:'custom_pending',label:kind==='external-port'?'Custom external port':'Custom cavity',family:'Custom',unit_system:ctx.get()?.project_context||'metric',manufacturer:'',thread_note:'',
    stages:[{start:0,end:20,diameter:20}],zones:[{id:'port1',start:10,end:18,diameter:18,offset_u:0,offset_v:0,clip_to_cut:true}],
    clearance_diameter:24,clearance_height:20,cutting_primitives:[],boundaries:[],machining:[],usable:true,unusable_reason:'',active:true,kind});

  function validationErrors(definition){
    const errors=[];
    definition.stages.forEach((row,index)=>{
      if(!(row.end>row.start))errors.push(`Stage ${index+1}: end depth must be greater than start depth.`);
      if(index===0&&Math.abs(row.start)>1e-6)errors.push('Stage 1 must start at depth 0.');
      if(index&&Math.abs(row.start-definition.stages[index-1].end)>1e-6)errors.push(`Stage ${index+1}: start depth must equal the previous end depth.`);
      if(index&&row.diameter>definition.stages[index-1].diameter)errors.push(`Stage ${index+1}: diameter cannot increase with depth.`);
    });
    const ids=new Set();
    definition.zones.forEach((row,index)=>{
      if(ids.has(row.id))errors.push(`Interface ${index+1}: duplicate interface ID.`);ids.add(row.id);
      if(!(row.end>row.start))errors.push(`Interface ${index+1}: end depth must be greater than start depth.`);
      if(!definition.cutting_primitives.length&&!definition.stages.some(stage=>stage.start<=row.start&&row.end<=stage.end&&row.diameter<=stage.diameter))errors.push(`Interface ${index+1}: hydraulic window must lie inside a machining stage.`);
    });
    definition.cutting_primitives.forEach((row,index)=>{if(!(row.end>row.start))errors.push(`Cutting primitive ${index+1}: end depth must be greater than start depth.`);if(row.kind==='annulus'&&!(row.inner_diameter<row.diameter))errors.push(`Cutting primitive ${index+1}: inner diameter must be smaller than outer diameter.`);});
    const outer=Math.max(0,...definition.stages.map(row=>row.diameter),...definition.cutting_primitives.map(row=>2*Math.hypot(row.offset_u||0,row.offset_v||0)+Math.max(row.diameter||0,row.end_diameter||0)));
    if(definition.clearance_diameter<outer)errors.push(`Clearance diameter must cover the ${outer.toFixed(2)} mm outer profile.`);
    definition.boundaries.forEach((row,index)=>{if(row.circle&&!(row.circle[2]>0))errors.push(`Boundary ${index+1}: circle radius must be positive.`);if(!row.circle&&(row.points||[]).length<3)errors.push(`Boundary ${index+1}: polygon requires at least three points.`);});
    if(definition.kind==='external-port'&&(definition.zones.length!==1||definition.zones[0]?.offset_u||definition.zones[0]?.offset_v))errors.push('External port requires exactly one centered hydraulic interface.');
    if(!definition.label.trim())errors.push('Enter a display name.');return errors;
  }

  function editCustom(source=null,backOptions={},requestedKind=null,{editing=false,revision=null}={}){
    ++generation;const kind=requestedKind||source?.kind||'cavity',noun=kind==='external-port'?'External Port':'Cavity',definition=structuredClone(source||blank(kind));definition.id='custom_pending';definition.kind=kind;definition.active=true;definition.usable=true;definition.unusable_reason='';
    const render=()=>{
      show(`Engineering Library / ${kind==='external-port'?'External Ports':'Cavities'} / ${editing?'Edit Custom':source?'Duplicate as Custom':'New Custom'}`);content.append(element('p',editing?'Saving changes creates a new version. Existing projects retain the previous machining definition.':'Save a reusable custom machining definition. The original definition remains unchanged.'));
      const edit=(parent,label,value,set,options=null,numeric=false)=>field(parent,label,value,v=>{set(v);render();},options,numeric);
      const basics=element('section',null,'editor-grid');content.append(basics);
      edit(basics,'Display name',definition.label,v=>definition.label=v);edit(basics,'Engineering units',definition.unit_system,v=>definition.unit_system=v,{metric:'Metric',inch:'Inch',custom:'Custom'});edit(basics,'Family / type',definition.family,v=>definition.family=v);edit(basics,'Manufacturer',definition.manufacturer,v=>definition.manufacturer=v);edit(basics,'Thread / note',definition.thread_note,v=>definition.thread_note=v);edit(basics,'Clearance diameter / mm',definition.clearance_diameter,v=>definition.clearance_diameter=v,null,true);edit(basics,'Clearance height / mm',definition.clearance_height,v=>definition.clearance_height=v,null,true);for(const message of validationErrors(definition).filter(value=>value.startsWith('Clearance diameter')))basics.append(element('p',message,'error'));

      const rowActions=(parent,rows,index,make)=>{const bar=element('div',null,'action-row');parent.append(bar);action(bar,'Duplicate',()=>{rows.splice(index+1,0,structuredClone(rows[index]));render();});action(bar,'Move up',()=>{if(index){[rows[index-1],rows[index]]=[rows[index],rows[index-1]];render();}});action(bar,'Move down',()=>{if(index<rows.length-1){[rows[index+1],rows[index]]=[rows[index],rows[index+1]];render();}});action(bar,'Delete',()=>{rows.splice(index,1);if(!rows.length&&make&&rows===definition.stages)rows.push(make());render();});};
      const section=(title,rows,make,build)=>{const singular={ 'Machining stages':'Machining stage','Cutting primitives':'Cutting primitive','Hydraulic interfaces':'Hydraulic interface','Supported boundaries':'Supported boundary','Machining operations':'Machining operation'}[title]||title;const box=element('section',null,'library-card');box.append(element('h3',`${title} · ${rows.length}`));content.append(box);rows.forEach((item,index)=>{const row=element('section',null,'port-row');row.append(element('h4',`${singular} ${index+1}`));box.append(row);build(row,item,index);rowActions(row,rows,index,make);});action(box,`+ Add ${singular.toLowerCase()}`,()=>{rows.push(make());render();});};

      section('Machining stages',definition.stages,()=>{const previous=definition.stages.at(-1);return {start:previous?.end||0,end:(previous?.end||0)+10,diameter:previous?.diameter||10};},(row,item,index)=>{const type=field(row,'Type','Cylinder',()=>{},{cylinder:'Cylinder'});type.disabled=true;edit(row,'Start depth / mm',item.start,v=>item.start=v,null,true);edit(row,'End depth / mm',item.end,v=>item.end=v,null,true);edit(row,'Diameter / mm',item.diameter,v=>item.diameter=v,null,true);for(const message of validationErrors(definition).filter(value=>value.startsWith(`Stage ${index+1}:`)))row.append(element('p',message,'error'));});
      section('Cutting primitives',definition.cutting_primitives,()=>({kind:'cylinder',start:0,end:10,diameter:10,end_diameter:10,inner_diameter:0,offset_u:0,offset_v:0,source_ref:'Custom'}),(row,item,index)=>{edit(row,'Type',item.kind,v=>item.kind=v,{cylinder:'Cylinder',cone:'Cone',annulus:'Annulus'});edit(row,'Start depth / mm',item.start,v=>item.start=v,null,true);edit(row,'End depth / mm',item.end,v=>item.end=v,null,true);edit(row,'Diameter / mm',item.diameter,v=>item.diameter=v,null,true);if(item.kind==='cone')edit(row,'End diameter / mm',item.end_diameter,v=>item.end_diameter=v,null,true);if(item.kind==='annulus')edit(row,'Inner diameter / mm',item.inner_diameter,v=>item.inner_diameter=v,null,true);edit(row,'Offset U / mm',item.offset_u||0,v=>item.offset_u=v,null,true);edit(row,'Offset V / mm',item.offset_v||0,v=>item.offset_v=v,null,true);for(const message of validationErrors(definition).filter(value=>value.startsWith(`Cutting primitive ${index+1}:`)))row.append(element('p',message,'error'));});
      section('Hydraulic interfaces',definition.zones,()=>({id:`port${definition.zones.length+1}`,start:0,end:5,diameter:5,offset_u:0,offset_v:0,clip_to_cut:true}),(row,item,index)=>{edit(row,'Interface name',item.id,v=>item.id=v);edit(row,'Start depth / mm',item.start,v=>item.start=v,null,true);edit(row,'End depth / mm',item.end,v=>item.end=v,null,true);edit(row,'Hydraulic diameter / mm',item.diameter,v=>item.diameter=v,null,true);edit(row,'Offset U / mm',item.offset_u||0,v=>item.offset_u=v,null,true);edit(row,'Offset V / mm',item.offset_v||0,v=>item.offset_v=v,null,true);edit(row,'Clip to machining volume',String(!!item.clip_to_cut),v=>item.clip_to_cut=v==='true',{true:'Yes',false:'No'});for(const message of validationErrors(definition).filter(value=>value.startsWith(`Interface ${index+1}:`)))row.append(element('p',message,'error'));});
      section('Supported boundaries',definition.boundaries,()=>({category:'mounting-footprint',circle:[0,0,10],points:[],height:0}),(row,item,index)=>{const type=item.circle?'circle':'polygon';edit(row,'Boundary type',type,v=>{if(v==='circle'){item.circle=[0,0,10];item.points=[];}else{item.circle=null;item.points=[[0,0],[10,0],[0,10]];}},{circle:'Circle',polygon:'Polygon'});edit(row,'Category',item.category,v=>item.category=v,{'mounting-footprint':'Mounting footprint','external-body':'External body',service:'Service',tool:'Tool'});edit(row,'Height / mm',item.height||0,v=>item.height=v,null,true);if(item.circle){for(const [i,label]of ['Center U / mm','Center V / mm','Radius / mm'].entries())edit(row,label,item.circle[i],v=>item.circle[i]=v,null,true);}else{for(const [i,point]of (item.points||[]).entries()){const pointRow=element('div',null,'field-row');row.append(pointRow);edit(pointRow,`Point ${i+1} U`,point[0],v=>point[0]=v,null,true);edit(pointRow,`Point ${i+1} V`,point[1],v=>point[1]=v,null,true);action(pointRow,'Delete point',()=>{item.points.splice(i,1);render();});}action(row,'+ Add polygon point',()=>{item.points.push([0,0]);render();});}for(const message of validationErrors(definition).filter(value=>value.startsWith(`Boundary ${index+1}:`)))row.append(element('p',message,'error'));});
      section('Machining operations',definition.machining,()=>({operation:'',tool:'',depth:null,note:'',source:''}),(row,item)=>{edit(row,'Operation',item.operation||'',v=>item.operation=v);edit(row,'Tool / cutter',engineeringName(item.tool,''),v=>item.tool=v);edit(row,'Depth / mm',item.depth??'',v=>item.depth=v===''?null:v,null,true);edit(row,'Note',item.note||'',v=>item.note=v);});

      const errors=validationErrors(definition);if(errors.length){const box=element('section',null,'error');box.append(element('strong','Correct these fields before saving:'));for(const value of errors)box.append(element('p',value));content.append(box);}profileEditor(ctx,content,definition,{editable:false});
      const buttons=element('div',null,'action-row');content.append(buttons);const returnToCategory=()=>backToCategory(kind==='external-port'?'external-ports':'cavities',backOptions);const save=action(buttons,editing?'Save changes':`Save New Custom ${noun}`,guard(async()=>{const invalid=validationErrors(definition);if(invalid.length)throw Error(invalid[0]);const saved=await post(editing?'/api/catalog/custom-definition/edit':kind==='external-port'?'/api/catalog/custom-external-port':'/api/catalog/custom-cavity',editing?{id:source.id,expected_revision:revision,definition}:{definition});if(kind==='cavity')onCustomSaved(saved);show(`Engineering Library / ${kind==='external-port'?'External Ports':'Cavities'}`);content.append(element('h3',saved.label),element('p',`${unitLabel(saved.unit_system)} · ${saved.family||'Custom'} · Available`));if(editing)content.append(element('p','Changes saved as a new version. Existing projects keep their previous definition.'));if(kind==='cavity')placement(content,'Place this cavity',()=>insert(saved));else if(backOptions.selectionMode==='external-port'&&backOptions.onSelect)action(content,'Use this external port',()=>backOptions.onSelect(saved));action(content,`Back to ${kind==='external-port'?'External Ports':'Cavities'}`,returnToCategory);}));save.classList.add('primary');save.disabled=!!errors.length;action(buttons,'Cancel',returnToCategory);
    };render();
  }

  const labels={cavities:'Cavities',cartridges:'Cartridges','external-ports':'External Ports',threads:'Threads',materials:'Materials & Stock',tooling:'Tooling',closures:'Closures & Plugs',modifiers:'Machining Modifiers'};
  const descriptions={cavities:'Browse cavity machining definitions and hydraulic interfaces.',cartridges:'Browse valve models, engineering properties and compatible cavities.','external-ports':'Browse hydraulic port machining and sealing forms.',threads:'Browse thread designations and tap-drill dimensions.',materials:'Browse engineering materials and available stock sizes.',tooling:'Browse drills, flat-bottom drills and spotface cutters.',closures:'Browse construction closures and plugs.',modifiers:'Browse O-ring grooves, counterbores and undercuts.'};
  const state={cavities:{q:'',unit:'',kind:'cavity',family:'',manufacturer:'',thread:'',status:'all',scope:'all',include_deleted:false,offset:0,limit:30},cartridges:{q:'',offset:0,limit:50},'external-ports':{q:'',unit:'',standard:'',kind:'port_definition',scope:'all',status:'all',include_deleted:false,offset:0,limit:50},threads:{q:'',unit:'',family:'',usable_only:false,offset:0,limit:40},materials:{q:'',status:'all',offset:0,limit:30},tooling:{q:'',type:'',unit:'',diameter:'',status:'all',offset:0,limit:30},closures:{q:'',status:'all',offset:0,limit:30},modifiers:{q:'',kind:'',unit:'',status:'all',offset:0,limit:30}};
  const selectionState={cavities:{...state.cavities},'external-ports':{...state['external-ports']}};
  const scroll={},local=record=>record.id.startsWith('custom_')||record.id.startsWith('legacy_');
  const displayMm=value=>value==null?'—':Number(Number(value).toFixed(4));
  function show(title){library.currentTitle=title;open(title);}
  function rememberScroll(category){scroll[category]=scrollContainer()?.scrollTop||0;}
  function restoreScroll(category){const node=scrollContainer();if(node)node.scrollTop=scroll[category]||0;}
  function backToCategory(category,options={}){const next={...options,entryCategory:category};delete next.recordId;return library(next);}
  function selectionCallback(port,options){if(port)return options.selectionMode==='external-port'?options.onSelect:null;if(options.selectionMode==='cavity')return options.onSelect||null;return !options.selectionMode||options.selectionMode==='browse'?insert:null;}
  const statusChoices={all:'All records',usable:'Available',unavailable:'Machining incomplete'};
  const units={'':'All units',metric:'Metric',inch:'Inch',custom:'Custom'};
  function heading(category,options={}){show(options.title||'Engineering Library / '+labels[category]);}

  function home(){
    const token=++generation;show('Engineering Library');content.append(element('p','Choose an engineering category.','library-description'));
    const grid=element('div',null,'library-category-grid');content.append(grid);
    const counts={cavities:async()=>(await api('/api/catalog?kind=cavity&limit=1')).total,cartridges:async()=>(await api('/api/cartridges?limit=1')).total,'external-ports':async()=>(await api('/api/catalog?kind=port_definition&limit=1')).total,threads:async()=>(await api('/api/threads?usable_only=false&limit=1')).total,materials:async()=>(await api('/api/materials')).items.filter(row=>row.selectable!==false).length,tooling:async()=>{const rows=await Promise.all(['drill','flat-bottom-drill','spotface'].map(type=>api('/api/tools?'+new URLSearchParams({type,usable_only:false}))));return rows.reduce((total,row)=>total+(row.total??row.items.length),0);},closures:async()=>(await api('/api/closures')).total,modifiers:async()=>(await api('/api/machining-modifiers?usable_only=false')).total};
    for(const key of Object.keys(labels)){const card=element('section',null,'library-card library-category-card'),count=element('p','Loading records…','library-category-count'),status=element('p','Checking availability…','property-note');card.append(element('h3',labels[key]),count,element('p',descriptions[key]),status);grid.append(card);action(card,'Browse',()=>backToCategory(key));Promise.resolve().then(counts[key]).then(total=>{if(token!==generation)return;count.textContent=Number(total).toLocaleString()+' records';status.textContent=total?'Available for browsing':'No records available';}).catch(()=>{if(token===generation){count.textContent='Count unavailable';status.textContent='Browse to retry';}});}
  }

  async function getRecord(id){return api('/api/catalog/record?'+new URLSearchParams({id}));}
  async function deleteRecord(definition,revision,category,options){
    const features=ctx.currentDefinitions?.()||ctx.get()?.features||[];
    if(features.some(feature=>(feature.cavity_id||feature.port_definition_id)===definition.id))throw Error('This record is used by the current draft. Archive it instead.');
    const name=prompt('Delete “'+definition.label+'” permanently? Type its exact name to confirm. Referenced records cannot be deleted.');if(name===null)return;if(name!==definition.label)throw Error('The record name did not match. Nothing was deleted.');
    await post('/api/catalog/custom-definition/delete',{id:definition.id,expected_revision:revision,confirm_name:name});return backToCategory(category,options);
  }
  function lifecycle(parent,definition,revision,category,options={}){
    if(options.readOnly)return;
    const isLocal=local(definition),items=[];
    if(isLocal)items.push(['Edit',()=>editCustom(definition,options,null,{editing:true,revision})]);
    items.push([isLocal?'Duplicate':'Duplicate as Custom',()=>editCustom(definition,options)]);
    if(isLocal){items.push([definition.active?'Archive':'Restore',guard(async()=>{await post('/api/library/visibility',{id:definition.id,deleted:!!definition.active});backToCategory(category,options);})]);items.push(['Delete',guard(()=>deleteRecord(definition,revision,category,options))]);}
    recordMore(ctx,parent,items);
  }
  async function viewDefinition(definition,options={}){
    const category=options.entryCategory||(definition.kind==='external-port'?'external-ports':'cavities'),token=++generation;
    show('Engineering Library / '+labels[category]+' / '+engineeringName(definition.label,'Machining definition'));action(content,'Back to '+labels[category],()=>backToCategory(category,options));
    content.append(element('p',`${local(definition)?'CUSTOM / LOCAL':'MASTER'} · ${availability(definition)} · ${unitLabel(definition.unit_system)} · ${definition.family||'Family not specified'}`));
    if(definition.manufacturer)content.append(element('p',definition.manufacturer));if(!definition.usable)content.append(element('p','Machining definition incomplete. Select an available definition before placement.','error'));
    profileEditor(ctx,content,definition,{editable:false,interfaceNames:options.interfaceNames||{}});
    const actions=element('div',null,'action-row');content.append(actions);const port=definition.kind==='external-port',select=selectionCallback(port,options);
    if(definition.active&&definition.usable&&!options.readOnly&&select)selectOrPlace(actions,options.actionLabel||(port?'Use External Port':'Place Cavity'),()=>select(definition),options);
    const metadata=await getRecord(definition.id);if(token!==generation)return;lifecycle(actions,definition,metadata.revision,category,options);
    if(!port){const compatible=element('section');content.append(compatible);compatible.append(element('h3','Compatible cartridges'));try{const result=await api('/api/cavities/'+encodeURIComponent(definition.id)+'/cartridges');if(token!==generation)return;for(const row of result.items){const line=element('div',null,'action-row');line.append(element('span',[row.manufacturer,row.model].filter(Boolean).join(' ')));action(line,'View',guard(()=>cartridgeDetail(row,{entryCategory:'cartridges'})));compatible.append(line);}if(!result.items.length)compatible.append(element('p','Not available'));}catch{if(token===generation)compatible.append(element('p','Compatibility not available.'));}}
  }

  async function definitionsCategory(category,options={}){
    const port=category==='external-ports',query=options.selectionMode?selectionState[category]:state[category],token=++generation;heading(category,options);
    const shell=libraryBrowser(ctx,content,{description:descriptions[category],back:home,create:options.readOnly?null:()=>editCustom(null,{...options,entryCategory:category},port?'external-port':'cavity')});let timer,request=0;
    const load=async()=>{const current=++request;shell.count.textContent='Loading records…';try{const result=await api('/api/catalog?'+new URLSearchParams(query));if(token!==generation||current!==request)return;shell.count.textContent=result.total.toLocaleString()+' records';shell.rows(['Name','Manufacturer','Family','Units','Scope','Status'],result.items,(row,buttons)=>{action(buttons,'View',guard(async()=>{rememberScroll(category);const data=await getRecord(row.id);if(token!==generation)return;return viewDefinition(data.definition,{...options,entryCategory:category});}));if(!options.readOnly){const items=[];if(local(row))items.push(['Edit',guard(async()=>{const data=await getRecord(row.id);if(token===generation)editCustom(data.definition,{...options,entryCategory:category},null,{editing:true,revision:data.revision});})]);items.push([local(row)?'Duplicate':'Duplicate as Custom',guard(async()=>{const data=await getRecord(row.id);if(token===generation)editCustom(data.definition,{...options,entryCategory:category});})]);if(local(row)){items.push([row.active?'Archive':'Restore',guard(async()=>{await post('/api/library/visibility',{id:row.id,deleted:!!row.active});if(token===generation)load();})]);items.push(['Delete',guard(async()=>{const data=await getRecord(row.id);if(token===generation)await deleteRecord(data.definition,data.revision,category,options);} )]);}recordMore(ctx,buttons,items);}
      if(options.selectionMode&&row.active&&row.usable&&options.onSelect)action(buttons,options.actionLabel||'Select',guard(async()=>{const data=await getRecord(row.id);if(token===generation)options.onSelect(data.definition);}));return [engineeringName(row.name,'Machining definition'),row.manufacturer,row.family,unitLabel(row.unit_system),local(row)?'CUSTOM / LOCAL':'MASTER',availability(row)];});shell.paging(query.offset,result.total,query.limit,offset=>{query.offset=offset;scroll[category]=0;load();});restoreScroll(category);}catch(error){if(token===generation&&current===request)shell.failure('Records could not be loaded. '+engineeringText(error.message),load);}};
    const update=(key,value)=>{query[key]=value;query.offset=0;scroll[category]=0;clearTimeout(timer);timer=setTimeout(load,160);};
    const search=field(shell.filters,'Search',query.q,value=>update('q',value));search.oninput=()=>update('q',search.value);
    field(shell.filters,'Scope',query.scope,value=>update('scope',value),{all:'Master and custom',master:'Master',custom:'Custom / local'});field(shell.filters,'Status',query.status,value=>update('status',value),statusChoices);field(shell.filters,'Units',query.unit,value=>update('unit',value),units);
    if(!port){field(shell.filters,'Manufacturer',query.manufacturer,value=>update('manufacturer',value));field(shell.filters,'Family',query.family,value=>update('family',value));field(shell.filters,'Thread',query.thread,value=>update('thread',value));}
    else field(shell.filters,'Port standard',query.standard,value=>update('standard',value),{'':'All',...Object.fromEntries(['BSPP','BSPT','NPT','NPTF','SAE_ORB','ISO_6149','SAE_J518','OTHER'].map(value=>[value,value.replaceAll('_',' ')]))});
    field(shell.filters,'Include archived',query.include_deleted,value=>update('include_deleted',value),{false:'No',true:'Yes'});await load();
  }

  async function cartridgeDetail(cartridge,options={}){
    const category='cartridges',token=++generation;rememberScroll(category);show('Engineering Library / Cartridges');action(content,'Back to Cartridges',()=>backToCategory(category,options));
    const identity=element('section',null,'library-card'),properties=element('section'),compatible=element('section'),knowledge=element('section');content.append(identity,properties,compatible,knowledge);
    try{cartridge=await api('/api/cartridges/'+encodeURIComponent(cartridge.id));if(token!==generation)return;identity.append(element('h3',[cartridge.manufacturer,cartridge.model].filter(Boolean).join(' ')),element('p',cartridge.function||'Function not available'),element('p','Read-only catalogue'));}
    catch{if(token===generation)identity.append(element('p',engineeringName(cartridge.model,'Cartridge')));}
    const tasks=[(async()=>{try{const data=await api('/api/cartridges/'+encodeURIComponent(cartridge.id)+'/engineering-facts');if(token===generation)engineeringFactsUI(ctx,properties,data,{title:'Engineering properties'});}catch{if(token===generation)properties.append(element('p','Engineering properties not available.'));}})(),(async()=>{compatible.append(element('h3','Compatible cavities'));try{const rows=await api('/api/cartridges/'+encodeURIComponent(cartridge.id)+'/cavities');if(token!==generation)return;for(const definition of rows){const line=element('div',null,'action-row');line.append(element('span',`${definition.label} · ${unitLabel(definition.unit_system)} · ${availability(definition)}`));action(line,'View',guard(()=>viewDefinition(definition,{entryCategory:'cavities',readOnly:true})));compatible.append(line);}if(!rows.length)compatible.append(element('p','Not available'));}catch{if(token===generation)compatible.append(element('p','Not available'));}})(),relationKnowledgeUI(ctx,knowledge,cartridge.id,()=>token===generation)];await Promise.all(tasks);
  }
  async function cartridges(options={}){
    const category='cartridges',query=state[category],token=++generation;heading(category,options);const shell=libraryBrowser(ctx,content,{description:descriptions[category],back:home,readOnly:true});let request=0,timer;
    const load=async()=>{const current=++request;try{const result=await api('/api/cartridges?'+new URLSearchParams({q:query.q,offset:query.offset,limit:query.limit}));if(token!==generation||current!==request)return;shell.count.textContent=result.total.toLocaleString()+' records';shell.rows(['Manufacturer','Model','Function','Status'],result.items,(row,buttons)=>{action(buttons,'View',guard(()=>cartridgeDetail(row,options)));return [row.manufacturer,engineeringName(row.model,'Cartridge'),row.function,availability(row)];});shell.paging(query.offset,result.total,query.limit,offset=>{query.offset=offset;scroll[category]=0;load();});restoreScroll(category);}catch(error){if(token===generation&&current===request)shell.failure('Cartridges could not be loaded. '+engineeringText(error.message),load);}};
    const search=field(shell.filters,'Search',query.q,value=>{query.q=value;query.offset=0;});search.oninput=()=>{query.q=search.value;query.offset=0;scroll[category]=0;clearTimeout(timer);timer=setTimeout(load,160);};await load();
  }

  async function readonlyDetail(category,row,options={}){
    rememberScroll(category);++generation;show('Engineering Library / '+labels[category]+' / '+engineeringName(row.display_name||row.name||row.model,labels[category]));action(content,'Back to '+labels[category],()=>backToCategory(category,options));const card=element('section',null,'library-card');content.append(card);card.append(element('p',availability(row)+' · Read-only catalogue'));
    const line=(label,value)=>{if(value!==null&&value!==undefined&&value!=='')card.append(element('p',label+': '+engineeringName(String(value),'Not specified')));};
    if(category==='threads'){line('Designation',row.display_name);line('Family',row.normalized_family||row.family);line('Size / pitch',row.pitch_tpi||row.nominal_size);line('Units',unitLabel(row.unit_system));line('Tap drill',row.tap_diameter_mm==null?'Not available':`Ø${displayMm(row.tap_diameter_mm)} mm`);line('Thread class',row.thread_class);line('Applicability',row.applicability);line('Form',row.tapered?'Tapered':'Parallel');}
    if(category==='materials'){line('Material',row.display_name);line('Type',row.material_type);engineeringFactsUI(ctx,card,row.engineering_facts_summary,{title:'Material properties'});card.append(element('h3','Available stock sizes'));for(const stock of row.stock||[])card.append(element('p',`${stock.size_1_mm} × ${stock.size_2_mm} mm · ${unitLabel(stock.unit_system)} · machining allowance ${stock.allowance_1_mm} × ${stock.allowance_2_mm} mm · ${stock.active?'Available':'Archived'}`));if(!row.stock?.length)card.append(element('p','No stock sizes available.'));}
    if(category==='tooling'){line('Type',row.tool_type.replaceAll('-',' '));line('Units',unitLabel(row.unit_system));line('Diameter',`Ø${displayMm(row.diameter_mm)} mm`);line('Maximum depth',`${displayMm(row.max_depth_mm)} mm`);}
    if(category==='closures'){line('Name',row.display_name);line('Model',row.model);line('Construction port',row.construction_port_name||'Not specified');line('Engagement',row.engagement_mm==null?'Not available':`${displayMm(row.engagement_mm)} mm`);card.append(element('h3','Envelope'));machiningRecipe(ctx,card,Array.isArray(row.envelope)?row.envelope:[row.envelope||{}]);card.append(element('h3','Machining'));machiningRecipe(ctx,card,row.machining);}
    if(category==='modifiers'){line('Name',row.display_name);line('Type',row.kind.replaceAll('-',' '));line('Units',unitLabel(row.unit_system));card.append(element('h3','Profile'));machiningRecipe(ctx,card,row.primitives);card.append(element('h3','Machining'));machiningRecipe(ctx,card,row.machining);}
  }

  async function readonlyCategory(category,options={}){
    const query=state[category],token=++generation;heading(category,options);const shell=libraryBrowser(ctx,content,{description:descriptions[category],back:home,readOnly:true});let request=0,timer;
    const fetchRows=async()=>{if(category==='materials')return (await api('/api/materials')).items.filter(row=>row.selectable!==false);if(category==='tooling')return (await Promise.all(['drill','flat-bottom-drill','spotface'].map(type=>api('/api/tools?'+new URLSearchParams({type,usable_only:false}))))).flatMap(result=>result.items);if(category==='closures')return (await api('/api/closures')).items;return (await api('/api/machining-modifiers?usable_only=false')).items;};
    const columns={materials:['Material','Type','Stock sizes','Status'],tooling:['Tool','Diameter / mm','Max depth / mm','Units','Status'],closures:['Name','Model','Construction port','Status'],modifiers:['Name','Type','Units','Status']};
    const load=async()=>{const current=++request;try{const all=await fetchRows();if(token!==generation||current!==request)return;const matches=all.filter(row=>{if(query.q&&!([row.display_name,row.name,row.model,row.material_type,row.tool_type,row.kind].join(' ').toLowerCase().includes(query.q.trim().toLowerCase())))return false;if(query.status==='usable'&&(row.usable===false||row.usable===0||row.active===false||row.active===0))return false;if(query.status==='unavailable'&&row.usable!==false&&row.usable!==0)return false;if(query.unit&&query.unit!==row.unit_system||query.type&&query.type!==row.tool_type||query.kind&&query.kind!==row.kind)return false;if(query.diameter&&!String(row.diameter_mm).includes(query.diameter))return false;return true;});query.offset=Math.max(0,Math.min(query.offset,Math.max(0,Math.ceil(matches.length/query.limit)-1)*query.limit));shell.count.textContent=matches.length.toLocaleString()+' records';shell.rows(columns[category],matches.slice(query.offset,query.offset+query.limit),(row,buttons)=>{action(buttons,'View',()=>readonlyDetail(category,row,options));if(category==='materials')return [row.display_name,row.material_type,(row.stock||[]).length,availability(row)];if(category==='tooling')return [row.tool_type.replaceAll('-',' '),displayMm(row.diameter_mm),displayMm(row.max_depth_mm),unitLabel(row.unit_system),availability(row)];if(category==='closures')return [row.display_name,row.model,row.construction_port_name,availability(row)];return [row.display_name,row.kind.replaceAll('-',' '),unitLabel(row.unit_system),availability(row)];});shell.paging(query.offset,matches.length,query.limit,offset=>{query.offset=offset;scroll[category]=0;load();});restoreScroll(category);}catch(error){if(token===generation&&current===request)shell.failure('Records could not be loaded. '+engineeringText(error.message),load);}};
    const update=(key,value)=>{query[key]=value;query.offset=0;scroll[category]=0;clearTimeout(timer);timer=setTimeout(load,160);};const search=field(shell.filters,'Search',query.q,value=>update('q',value));search.oninput=()=>update('q',search.value);field(shell.filters,'Status',query.status,value=>update('status',value),statusChoices);
    if(category==='tooling'||category==='modifiers'){field(shell.filters,'Units',query.unit,value=>update('unit',value),units);if(category==='tooling'){field(shell.filters,'Tool type',query.type,value=>update('type',value),{'':'All',drill:'Drill','flat-bottom-drill':'Flat-bottom drill',spotface:'Spotface'});field(shell.filters,'Diameter / mm',query.diameter,value=>update('diameter',value));}else field(shell.filters,'Form',query.kind,value=>update('kind',value),{'':'All','o-ring-groove':'O-ring groove',counterbore:'Counterbore',undercut:'Undercut'});}await load();
  }
  async function threads(options={}){
    const category='threads',query=state[category],token=++generation;heading(category,options);const shell=libraryBrowser(ctx,content,{description:descriptions[category],back:home,readOnly:true});let request=0,timer;
    const load=async()=>{const current=++request;try{const result=await api('/api/threads?'+new URLSearchParams(query));if(token!==generation||current!==request)return;shell.count.textContent=result.total.toLocaleString()+' records';shell.rows(['Designation','Family','Size / pitch','Units','Tap drill / mm','Status'],result.items,(row,buttons)=>{action(buttons,'View',()=>readonlyDetail(category,row,options));return [row.display_name,row.normalized_family||row.family,row.pitch_tpi||row.nominal_size,unitLabel(row.unit_system),displayMm(row.tap_diameter_mm),availability(row)];});shell.paging(query.offset,result.total,query.limit,offset=>{query.offset=offset;scroll[category]=0;load();});restoreScroll(category);}catch(error){if(token===generation&&current===request)shell.failure('Threads could not be loaded. '+engineeringText(error.message),load);}};
    const update=(key,value)=>{query[key]=value;query.offset=0;scroll[category]=0;clearTimeout(timer);timer=setTimeout(load,160);};const search=field(shell.filters,'Search',query.q,value=>update('q',value));search.oninput=()=>update('q',search.value);field(shell.filters,'Status',query.usable_only,value=>update('usable_only',value),{false:'All records',true:'Available'});field(shell.filters,'Units',query.unit,value=>update('unit',value),units);field(shell.filters,'Family',query.family,value=>update('family',value));await load();
  }
  function library(options={}){
    const category=options.entryCategory||'home';
    if(category==='cartridges'&&options.recordId)return cartridgeDetail({id:options.recordId},options);
    if(category==='materials'&&options.recordId)return api('/api/materials').then(result=>{const row=result.items.find(item=>item.id===options.recordId||item.technical_identity_id===options.recordId);if(row)return readonlyDetail(category,row,options);throw Error('Material not available.');});
    if(category==='home')return home();if(category==='cavities'||category==='external-ports')return definitionsCategory(category,options);if(category==='cartridges')return cartridges(options);if(category==='threads')return threads(options);if(['materials','tooling','closures','modifiers'].includes(category))return readonlyCategory(category,options);throw Error('Library category not available.');
  }
  library.invalidate=()=>{generation++;};return library;
}
