import {createPreviewQueue} from './preview-queue.js';
import {streamExactPreview} from './preview-stream.js';
import {isCavity} from './definition-role.js';
import './style.css';
import {createViewer} from './viewer.js';
import {clamp,syncNets,featureLabel} from './kinematics.js';
import {pose,axes} from './kinematics.js';
import {workflows} from './workflows.js';
import {projectLibrary} from './project-library.js';
import {hydrateDesign,cloneDesign} from './domain.js';
const $=id=>document.getElementById(id),colors={P:'#ef5959',T:'#459cff',A:'#41ca8b',B:'#f2d454'},faces=Object.fromEntries(['top','bottom','front','back','left','right'].map(f=>[f,f]));
let draftCheckedSignature=null,projectEpoch=0,savePending=null;
let viewMode='review',lastUsablePreview=null;
let state,draft,report,model,resolved,selection='block',dirty=false,busy=false,externalChange=false,viewer,history=[],future=[],dragStart,exactPreview=null;
const previewDiagnostics=[];globalThis.__PMC_PREVIEW_TIMINGS=previewDiagnostics;
function previewTiming(value){const row=Object.fromEntries(Object.entries(value).map(([k,v])=>[k,typeof v==='number'?Math.round(v*100)/100:v]));previewDiagnostics.push(row);if(previewDiagnostics.length>24)previewDiagnostics.shift();}
function element(tag,text,cls){const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;}
function notice(message,error=false){$('notice').textContent=message;$('notice').className=error?'error':'';}
async function api(url,options={}){
  const limit=['/api/build','/api/optimize-routes'].includes(url)?330000:url==='/api/refine-route'?65000:url==='/api/freeze-net'?35000:30000;
  try{
    const r=await fetch(url,{signal:AbortSignal.timeout(limit),...options});
    if(!r.ok){const b=await r.json().catch(()=>({}));throw Error(typeof b.detail==='string'?b.detail:Array.isArray(b.detail)?b.detail.map(e=>`${(e.loc||[]).filter(x=>x!=='body').join('.')}: ${e.msg}`).join('; '):JSON.stringify(b.detail||r.status));}
    return await r.json();
  }catch(error){if(error.name==='TimeoutError')throw Error('Request timed out. Draft and last usable view retained. Refresh project status before retrying a save or build.');throw error;}
}
const post=(url,body,options={})=>api(url,{...options,method:'POST',headers:{'Content-Type':'application/json','X-PMC-Request':'local-console',...options.headers},body:JSON.stringify(body)});
function change(fn){if(busy)return false;const before=cloneDesign(draft);try{fn();syncNets(draft);history.push(before);if(history.length>40)history.shift();future=[];markDirty();renderTree();select(selection);return true;}catch(e){draft=before;notice(e.message,true);select(selection);return false;}}
const solidOverlay=element('div',null,'viewport-loading');solidOverlay.setAttribute('role','status');solidOverlay.hidden=true;$('viewport').append(solidOverlay);
function solidStatus(text=''){solidOverlay.hidden=!text;solidOverlay.textContent=text;}
function previewState(kind,text){$('viewport').dataset.previewState=kind;$('model-info').textContent=text;}
function showSolid(result,snapshot=draft,context=null){solidStatus();resolved=hydrateDesign({...snapshot,features:result.features},draft.library);viewer?.setReferences(result.features);viewer?.load(result.model,result.features);viewer?.setDesign(draft);exactPreview=context&&result.model.deferred_layers?.length?{...context,designRevision:result.design_revision,pending:new Set()}:null;lastUsablePreview={model:result.model,design:resolved};renderTree();select(selection);previewState('exact-proposal','EXACT BREP · CURRENT PROPOSAL · NOT VALIDATED / NOT OPTIMIZED'+(result.model.brep_valid===false?' · BREP TOPOLOGY INVALID':''));notice(result.model.brep_valid===false?'Exact preview ready. Current proposal has invalid BRep topology; Save & Validate reports engineering failures.':'Exact preview ready. Current proposal is not validated or optimized.');requestLayer(viewMode);}
const previews=createPreviewQueue({post,stream:streamExactPreview,
  cancelRemote:(owner,version)=>post('/api/preview-cancel',{owner,version},{signal:AbortSignal.timeout(2000)}),
  onFast(p,snapshot){exactPreview=null;resolved=hydrateDesign(p.design,draft.library);viewer?.preview(resolved);viewer?.setReferences(resolved.features);viewer?.setDesign(draft);lastUsablePreview={design:resolved};renderTree();previewState('approximate','APPROXIMATE LIVE VIEW · CURRENT PROPOSAL · NOT VALIDATED');},
  onExact:showSolid,
  onTiming:previewTiming,
  onStatus(status){solidStatus(status==='exact'?'Computing exact current proposal… Not validated or optimized.':'');if(status==='exact')previewState('computing','APPROXIMATE LIVE VIEW · EXACT BREP COMPUTING · NOT VALIDATED');},
  onError(error){exactPreview=null;if(lastUsablePreview){const p=lastUsablePreview;if(p.model)viewer?.load(p.model,p.design.features);else viewer?.preview(p.design);viewer?.setDesign(p.design);}solidStatus();previewState('unavailable','EXACT PREVIEW UNAVAILABLE · PREVIEW FAILED · LAST USABLE VIEW RETAINED · '+(lastUsablePreview?.model?'EXACT':'APPROXIMATE')+' · '+error.message);notice('Preview: '+error.message,true);}
});
async function requestLayer(mode){
  const layer=mode==='void'?'void':mode==='features'?'features':null,token=exactPreview;
  if(!layer||!token||!viewer?.needsLayer(layer)||token.pending.has(layer))return;
  token.pending.add(layer);const started=performance.now();
  try{const result=await post('/api/preview-layer',{design_revision:token.designRevision,layer},{headers:{'X-PMC-Preview-Owner':token.owner,'X-PMC-Preview-Version':String(token.version)}});if(exactPreview!==token||result.design_revision!==token.designRevision||result.layer!==layer)return;viewer.loadLayer(layer,result.parts);previewTiming({kind:'lazy-layer-request',layer,total_ms:performance.now()-started});}
  catch(error){if(exactPreview===token)notice('Exact inspection layer unavailable: '+error.message,true);}
  finally{token.pending.delete(layer);}
}
function requestSolid(){
  if(!draft||dragStart||busy)return;
  if(!dirty&&!state?.stale&&state?.build){exactPreview=null;previews.cancel();if(model){viewer?.load(model,resolved.features);lastUsablePreview={model,design:resolved};}else{viewer?.preview(resolved);lastUsablePreview={design:resolved};}viewer?.setDesign(draft);previewState('authoritative','AUTHORITATIVE SAVE & VALIDATE · '+state.build.status+' · '+(model?'EXACT MACHINED BREP':'EXACT REVIEW UNAVAILABLE · APPROXIMATE VIEW'));return;}
  previews.schedule(draft,String(projectEpoch));
}
function refreshPreview(){
  solidStatus();
  try{viewer?.preview(draft);viewer?.setDesign(draft);previewState('approximate','APPROXIMATE LIVE VIEW · NOT VALIDATED');}
  catch(error){$('model-info').textContent='LAST USABLE VIEW RETAINED · '+error.message;}
  if(dragStart)previews.cancel();else requestSolid();
}
function markDirty(){draftCheckedSignature=null;dirty=true;exactPreview=null;renderHeader();refreshPreview();notice('Draft preview updated. Save & Validate runs exact geometry checks and writes an immutable build.');}
try{viewer=createViewer($('viewport'),select,(id,u,v,done)=>{if(busy)return;const f=draft.features.find(f=>f.id===id),starting=!dragStart;if(starting){dragStart=structuredClone(draft);previews.cancel();exactPreview=null;dirty=true;renderHeader();}f.u=u;f.v=v;$('selection-label').textContent=`${id} · ${f.face} · U ${u.toFixed(1)} / V ${v.toFixed(1)} mm`;notice('Live position · envelope clamped to face · 1 mm snap · preview is not validated');if(!done){viewer?.updateFeature(draft,id);previewState('approximate','APPROXIMATE LOCAL DRAG · NOT VALIDATED');return;}const baseline=dragStart;history.push(baseline);future=[];dragStart=null;select(id);if(f.frozen_net)refineAfterDrag(baseline,id,u,v);else refreshPreview();});$('viewport').addEventListener('pmc-viewer-timing',event=>previewTiming(event.detail));}catch(e){notice('WebGL: '+e.message,true);}

async function refineAfterDrag(baseline,id,u,v){
  const signature=JSON.stringify(draft);notice('Checking adjusted route and connected branches…');
  try{const result=await post('/api/refine-route',{design:baseline,feature_id:id,u,v});if(JSON.stringify(draft)!==signature)return;draft=hydrateDesign(result.design,draft.library);refreshPreview();report=result.report;draftCheckedSignature=JSON.stringify(draft);renderTree();select(id);renderReport();renderHeader();notice(`Draft exact checks: ${report.counts.PASS} PASS / ${report.counts.FAIL} FAIL. ${result.adjusted_branches.length} branches extended. ${result.notes.join(' ')} Save & Validate includes STEP round trip.`,report.status==='FAIL');}
  catch(e){if(JSON.stringify(draft)===signature){refreshPreview();notice('Route remains an unvalidated draft: '+e.message,true);}}
}
let adoptingRoute=false;
async function adoptRoute(netId,id=selection){
  if(adoptingRoute)return false;
  const displayed=lastUsablePreview,proposal=structuredClone(displayed?.design||resolved),baseline=JSON.stringify(draft),epoch=projectEpoch;
  if(!proposal){notice('No displayed proposal to refine. Wait for the preview.',true);return false;}
  adoptingRoute=true;previews.cancel();solidStatus('Adopting displayed route…');notice('Adopting displayed route… Keeping its geometry.');
  for(const b of document.querySelectorAll('button'))if(b.textContent==='Refine in 3D')b.disabled=true;
  try{
    const result=await post('/api/freeze-net',{design:structuredClone(draft),net:netId,proposal});
    if(projectEpoch!==epoch||JSON.stringify(draft)!==baseline)throw Error('Draft changed during adoption; refresh the preview and retry.');
    if(!change(()=>draft=hydrateDesign(result,draft.library)))throw Error('Could not adopt route while another operation is active.');
    previews.cancel();
    resolved={...proposal,nets:result.nets,features:[...proposal.features.filter(f=>f.route_net!==netId),...result.features.filter(f=>f.frozen_net===netId)]};
    if(displayed?.model)viewer?.load(displayed.model,resolved.features);else viewer?.preview(resolved);
    viewer?.setReferences(resolved.features);viewer?.setDesign(draft);lastUsablePreview={model:displayed?.model,design:resolved};
    $('model-info').textContent=(displayed?.model?'EXACT BREP':'CURRENT PROPOSAL')+' · REFINED / MANUAL · NOT VALIDATED';
    renderTree();select(id);notice('Refined / manual route · '+netId+' · Drag the selected drilling to edit. Geometry is unchanged; Save & Validate checks it.');return true;
  }catch(e){notice('Refine failed: '+e.message,true);return false;}
  finally{adoptingRoute=false;solidStatus();for(const b of document.querySelectorAll('button'))if(b.textContent==='Refine in 3D')b.disabled=false;}
}
function renderHeader(){if(!draft)return;const unbound=(draft.schematic_intent?.components||[]).filter(c=>!c.placement_id).length;$('review-open').textContent='Engineering Review · '+((draft.review_items||[]).filter(r=>r.status==='open').length+unbound);$('project-name').textContent=draft.name;const b=draft.block;$('dimensions').textContent=`${b.length} × ${b.width} × ${b.height} mm`;$('revision').textContent='SHA '+state.revision.slice(0,8);const status=dirty?'DRAFT':!state.build?'SAVED DRAFT':externalChange||state.stale?'STALE':state.build.status;$('status').textContent=status;$('status').className='badge '+(status==='FAIL'?'fail':status==='PASS'?'':'warning');for(const [id,name]of [['step-download','production.step'],['data-download','design.json'],['report-download','validation.md'],['chart-download','drill-chart.csv'],['manufacturing-download','manufacturing.json']]){const ok=!!state.build&&!dirty&&!state.stale&&!externalChange&&!busy&&(id!=='step-download'||status==='PASS');$(id).classList.toggle('disabled',!ok);if(ok)$(id).href=`/api/artifacts/${state.build.build_id}/${name}`;else $(id).removeAttribute('href');}$('build').textContent=busy?'Computing exact solids…':'Save & Validate';$('undo').disabled=busy||!history.length;$('redo').disabled=busy||!future.length;if(draftCheckedSignature===JSON.stringify(draft))$('check-counts').textContent=`Draft exact checks · ${report.counts.PASS} PASS / ${report.counts.FAIL} FAIL · not saved`;else if(dirty||state.stale)$('check-counts').textContent=report?'Previous build results · draft not validated':'Not validated';}
function renderTree(){const tree=$('feature-tree');tree.replaceChildren();$('feature-count').textContent=draft.features.length+' ITEMS';for(const kind of ['cavity','port','drilling','mounting']){const group=element('div',null,'tree-group'),list=draft.features.filter(f=>f.kind===kind);group.append(element('div',`${{cavity:'Cavities',port:'External ports',drilling:'Manual drillings',mounting:'Mounting holes'}[kind]} / ${list.length}`,'tree-heading'));for(const f of list){const btn=element('button',null,'tree-feature');btn.dataset.feature=f.id;const dot=element('span',null,'swatch');dot.style.background=colors[f.circuit]||'#b4c7da';btn.append(dot,element('span',featureLabel(f,draft)),element('small',f.suppressed?'SUPPRESSED':f.kind==='cavity'?Object.values(f.circuits).join(' / '):f.face));btn.onclick=()=>select(f.id);group.append(btn);}tree.append(group);}for(const f of resolved?.features.filter(f=>f.route_net&&!draft.features.some(x=>x.id===f.id))||[]){const b=element('button',`${f.id} · ${f.route_net}`,'tree-feature');b.dataset.feature=f.id;b.onclick=()=>select(f.id);tree.append(b);}$('circuits').replaceChildren();for(const n of draft.nets){const btn=element('button',n.id,'circuit-toggle');btn.style.borderColor=n.color||colors[n.id]||'#b08bea';btn.classList.toggle('off',viewer?!viewer.circuitVisible(n.id):false);btn.onclick=()=>{btn.classList.toggle('off');viewer.circuit(n.id,!btn.classList.contains('off'));};$('circuits').append(btn);}}
function field(parent,label,value,onChange,options=null,numeric=false){const wrap=element('label',label,'field'),input=document.createElement(options?'select':'input');input.setAttribute('aria-label',label);if(options)for(const [key,text]of Object.entries(options)){const o=element('option',text);o.value=key;input.append(o);}else{input.type=numeric?'number':'text';if(numeric)input.step='.1';}input.value=value??'';input.onchange=()=>{const v=numeric?input.valueAsNumber:input.value;if(numeric&&!Number.isFinite(v)){input.reportValidity();return;}onChange(v);};wrap.append(input);parent.append(wrap);return input;}
const prop=(p,l,v,fn,o=null,n=false)=>field(p,l,v,x=>change(()=>fn(x)),o,n);
function action(parent,label,fn){const b=element('button',label);b.type='button';b.onclick=fn;parent.append(b);return b;}
function newId(prefix){let i=1;while(draft.features.some(f=>f.id===prefix+i))i++;return prefix+i;}
function replaceCavity(f,id){
  const def=draft.library.find(d=>d.id===id);if(!def||!isCavity(def)){notice('Replacement must be a cavity.',true);return;}const mapping=Object.fromEntries(def.zones.map(z=>[z.id,f.circuits[z.id]||'']));
  const apply=()=>change(()=>{if(Object.values(mapping).some(n=>!n))throw Error('Choose a net for every new interface');f.definition=id;f.circuits={...mapping};f.cartridge_id=null;[f.u,f.v]=clamp(f,draft,f.u,f.v);const valid=new Set(def.zones.map(z=>`${f.id}:${z.id}`));for(const bore of draft.features)bore.connects_to=bore.connects_to.filter(t=>!t.startsWith(f.id+':')||valid.has(t));});
  if(def.zones.length===Object.keys(f.circuits).length&&Object.values(mapping).every(Boolean)){apply();return;}
  $('workflow-title').textContent='Replace cavity · confirm interface mapping';const box=$('workflow-content');box.replaceChildren(element('p','The new cavity has different hydraulic windows. Assign every new window explicitly. Removed windows will lose their physical contact declarations; schematic mapping must be reviewed.'));
  for(const z of def.zones)field(box,`New interface ${z.id}`,mapping[z.id],v=>mapping[z.id]=v,{'':'Select hydraulic net',...Object.fromEntries(draft.nets.map(n=>[n.id,n.id]))});
  action(box,'Apply replacement',()=>{if(Object.values(mapping).some(n=>!n)){$('workflow-error').textContent='Choose a net for every interface';return;}apply();$('workflow-dialog').close();});$('workflow-error').textContent='';$('workflow-dialog').showModal();select(f.id);
}
async function assignCartridge(f){
  $('workflow-title').textContent='Cartridge assignment · '+f.id;const box=$('workflow-content');box.replaceChildren(element('p','Only cartridges with an explicit database compatibility relationship are available. Leaving this empty is valid.'));$('workflow-error').textContent='';$('workflow-dialog').showModal();
  action(box,'No cartridge',()=>{change(()=>f.cartridge_id=null);$('workflow-dialog').close();select(f.id);});
  try{const result=await api('/api/cavities/'+encodeURIComponent(f.cavity_id)+'/cartridges');for(const row of result.items){const card=element('section',null,'library-card');card.append(element('h3',row.model),element('p',`${row.manufacturer||'Manufacturer unspecified'} · ${row.function||'Function unspecified'}\n${row.id}`));action(card,'Assign cartridge',()=>{change(()=>f.cartridge_id=row.id);$('workflow-dialog').close();select(f.id);});box.append(card);}if(!result.items.length)box.append(element('p','No compatible cartridges are present in the engineering database. The cavity remains valid without one.'));}catch(e){$('workflow-error').textContent=e.message;}
}
function remove(id){change(()=>{const ids=new Set([id]);let n;do{n=ids.size;for(const f of draft.features)if(ids.has(f.parent_id))ids.add(f.id);}while(ids.size!==n);draft.features=draft.features.filter(f=>!ids.has(f.id));for(const f of draft.features)f.connects_to=f.connects_to.filter(t=>!ids.has(t.split(':')[0]));for(const c of draft.components)if(ids.has(c.feature_id)){c.placement_id=null;c.cavity_id=null;}selection='block';});}
function select(id){if(!draft)return;const generated=resolved?.features.find(f=>f.id===id&&f.route_net&&!draft.features.some(x=>x.id===id));if(generated){selection=id;viewer?.select(id);$('selection-label').textContent=id+' · '+generated.route_net;$('selection-kind').textContent='GENERATED ROUTE';const form=$('inspector');form.replaceChildren(element('h3',id),element('p',`Net ${generated.route_net} · ${generated.face} · Ø${generated.diameter} × ${generated.depth.toFixed(2)} mm`),element('p','Refine this route to keep its current segments and drag drilling handles. Connected branches are extended where possible; exact checks decide whether the edited route still works.'));action(form,'Refine in 3D',()=>adoptRoute(generated.route_net,id));return;}selection=draft.features.some(f=>f.id===id)?id:'block';viewer?.select(selection);$('selection-label').textContent=selection==='block'?'':featureLabel(draft.features.find(f=>f.id===selection),draft);for(const b of document.querySelectorAll('[data-feature]'))b.classList.toggle('active',b.dataset.feature===selection);$('select-block').classList.toggle('active',selection==='block');const form=$('inspector');form.replaceChildren();form.onsubmit=e=>e.preventDefault();
if(selection==='block'){$('selection-kind').textContent='STOCK';form.append(element('div','MANIFOLD','inspector-title'));prop(form,'Project name',draft.name,v=>draft.name=v);for(const [key,label]of [['length','Length X / mm'],['width','Width Y / mm'],['height','Height Z / mm']])prop(form,label,draft.block[key],v=>draft.block[key]=v,null,true);prop(form,'Material',draft.block.material,v=>draft.block.material=v);prop(form,'Preferred extra wall margin / mm',draft.constraints.preferred_wall_margin,v=>draft.constraints.preferred_wall_margin=v,null,true);prop(form,'Minimum wall / mm',draft.rules.minimum_wall,v=>draft.rules.minimum_wall=v,null,true);prop(form,'Design priority',draft.constraints.priority,v=>draft.constraints.priority=v,{compact:'Compact envelope',fewer_plugs:'Fewer plugs',simple_machining:'Simpler machining',short_drills:'Shorter drillings'});prop(form,'Envelope limit X,Y,Z / mm',(draft.constraints.envelope_max||[]).join(', '),v=>draft.constraints.envelope_max=v.trim()?v.split(',').map(Number):null);prop(form,'Engineering notes',draft.constraints.notes,v=>draft.constraints.notes=v);form.append(element('p','Origin: left / front / bottom. Exact wall and intersection checks run on Save & Validate.','inspector-note'));}
else{const f=draft.features.find(f=>f.id===selection);const p=pose(f,draft.block),uv=axes[f.face];form.append(element('p',`Origin XYZ: ${p.origin.map(x=>x.toFixed(3)).join(', ')} mm · U=+${'XYZ'[uv[0]]}, V=+${'XYZ'[uv[1]]} · inward ${p.direction.join(', ')}`,'property-note'));$('selection-kind').textContent=f.kind.toUpperCase();form.append(element('div',featureLabel(f,draft),'inspector-title'));if(featureLabel(f,draft)!==f.id)form.append(element('p','Reference ID: '+f.id,'property-note'));if(f.frozen_net)form.append(element('p',`Refined route · ${f.frozen_net}. Drag anywhere along the drilling to check changes.${!f.plugged?' This entry uses a fixed external port; lateral moves may invalidate its closure.':''}`,'property-note'));const bar=element('div',null,'action-row');form.append(bar);action(bar,'Duplicate',()=>change(()=>{const copy=structuredClone(f);copy.id=newId(f.kind==='cavity'?'CV':f.kind==='port'?f.circuit.slice(0,36):'DRILL');copy.parent_id=null;copy.schematic_id='';copy.connects_to=[];[copy.u,copy.v]=clamp(copy,draft,copy.u+25,copy.v+20);draft.features.push(copy);selection=copy.id;}));action(bar,f.suppressed?'Restore':'Suppress',()=>change(()=>f.suppressed=!f.suppressed));action(bar,'Delete',()=>remove(f.id));prop(form,'Face',f.face,v=>{f.face=v;if(f.kind==='mounting'&&f.through)f.depth=[draft.block.length,draft.block.width,draft.block.height][axes[f.face][2]];[f.u,f.v]=clamp(f,draft,f.u,f.v);},faces);const row=element('div',null,'field-row');form.append(row);prop(row,'Position U / mm',f.u,v=>{[f.u,f.v]=clamp(f,draft,v,f.v);},null,true);prop(row,'Position V / mm',f.v,v=>{[f.u,f.v]=clamp(f,draft,f.u,v);},null,true);
if(f.kind==='cavity'){field(form,'Replace cavity',f.definition,v=>replaceCavity(f,v),Object.fromEntries(draft.library.filter(isCavity).map(d=>[d.id,d.label])));form.append(element('p','Cartridge: '+(f.cartridge_id||'None'),'property-note'));action(form,'Assign compatible cartridge',()=>assignCartridge(f));for(const key of Object.keys(f.circuits))prop(form,`Interface ${key} → Net`,f.circuits[key],v=>f.circuits[key]=v,Object.fromEntries(draft.nets.map(n=>[n.id,n.id])));const def=draft.library.find(d=>d.id===f.definition);form.append(element('p',`${def.manufacturer||'Manufacturer unspecified'} · ${def.family||'Family unspecified'}\n${def.id}\n${def.stages.map(s=>`Ø${s.diameter.toFixed(4)} / ${s.start.toFixed(4)}–${s.end.toFixed(4)} mm`).join('\n')}`,'property-note'));}
else if(f.kind==='mounting'){prop(form,'Diameter / mm',f.diameter,v=>f.diameter=v,null,true);prop(form,'Through hole',String(f.through),v=>{f.through=v==='true';if(f.through){f.tip_angle=180;f.depth=[draft.block.length,draft.block.width,draft.block.height][axes[f.face][2]];}},{true:'Through',false:'Blind'});if(!f.through){prop(form,'Cylinder depth / mm',f.depth,v=>f.depth=v,null,true);prop(form,'Drill point angle / degrees',f.tip_angle,v=>f.tip_angle=v,null,true);}form.append(element('p','Plain non-hydraulic mounting cut. No thread or fastener compatibility is inferred. Exact wall and interference checks apply.','property-note'));}
else{if(f.frozen_net)form.append(element('p',`Hydraulic owner: ${f.frozen_net}. Use Hydraulic Nets → Reroute before changing route intent.`,'property-note'));else prop(form,'Hydraulic net',f.circuit,v=>f.circuit=v,Object.fromEntries(draft.nets.map(n=>[n.id,n.id])));if(f.definition){const d=draft.library.find(d=>d.id===f.definition);form.append(element('p',d.label+' · '+d.id+' · SQLite machining definition','property-note'));const cuts=d.cutting_primitives?.length?d.cutting_primitives:d.stages;form.append(element('p',`Machining: ${cuts.length} mapped cuts · axial span ${Math.min(...cuts.map(s=>s.start)).toFixed(2)}–${Math.max(...cuts.map(s=>s.end)).toFixed(2)} mm.\nHydraulic window: ${d.zones.map(z=>`Ø${z.diameter.toFixed(2)} envelope at ${z.start.toFixed(2)}–${z.end.toFixed(2)} mm${z.clip_to_cut?' (clipped to machining)':''}`).join(', ')}.`,'property-note'));}else for(const key of ['diameter','depth'])prop(form,key==='diameter'?'Diameter / mm':'Cylinder depth / mm',f[key],v=>f[key]=v,null,true);if(f.kind==='port')prop(form,'Port specification',f.size,v=>f.size=v);else{prop(form,'Drill direction X,Y,Z (blank = face normal)',(f.direction||[]).join(', '),v=>f.direction=v.trim()?v.split(',').map(Number):null);prop(form,'Entry closure',String(f.plugged),v=>f.plugged=v==='true',{'true':'Plug','false':'Coaxial external port'});prop(form,'Drill point angle / degrees',f.tip_angle,v=>f.tip_angle=v,null,true);prop(form,'Plug engagement / mm',f.plug_length,v=>f.plug_length=v,null,true);if(f.plugged)form.append(element('p','Plug engagement is a declared closure volume. No source entry profile is bound; machining details remain unresolved.','property-note'));prop(form,'Expected contacts',f.connects_to.join(', '),v=>f.connects_to=v.split(',').map(s=>s.trim()).filter(Boolean));}}
const advanced=element('details');advanced.append(element('summary','Relationships & machining'));form.append(advanced);prop(advanced,'Rotation / degrees',f.rotation,v=>f.rotation=v,null,true);prop(advanced,'Parent feature',f.parent_id||'',v=>{f.parent_id=v||null;const p=draft.features.find(x=>x.id===v);if(p)f.local_offset=[f.u-p.u,f.v-p.v];},{'':'Independent',...Object.fromEntries(draft.features.filter(x=>x.id!==f.id).map(x=>[x.id,x.id]))});prop(advanced,'Machining ID',f.machining_id,v=>f.machining_id=v);advanced.append(element('p','Rotation moves attached offsets and native footprint cuts.','inspector-note'));for(const [n,t]of Object.entries(report?.graph||{}).filter(([n])=>n===f.id||n.startsWith(f.id+':')))form.append(element('div',`${n} → ${t.join(', ')||'Disconnected'} (last build)`,'property-note'));}
$('feature-results').replaceChildren();for(const c of (report?.checks||[]).filter(c=>c.status!=='PASS'&&c.items.some(i=>i.split(':')[0]===selection)))$('feature-results').append(element('div',`${c.status} · ${c.rule}: ${c.actual} / ${c.required} ${c.unit}`,'feature-check'));if($('report-filter').value==='selected')renderReport();}
function renderReport(){if(!report){$('check-counts').textContent='Not validated';$('validation-results').replaceChildren(element('p','Save & Validate to check this project.'));$('limitations').replaceChildren();$('build-time').textContent='';return;}$('check-counts').textContent=`${report.counts.PASS} PASS / ${report.counts.WARNING} WARNING / ${report.counts.FAIL} FAIL`;$('build-time').textContent=new Date(report.generated_at).toLocaleTimeString();$('limitations').replaceChildren(...report.limitations.map(s=>element('li',s)));const filter=$('report-filter').value,checks=report.checks.filter(c=>filter==='all'||(filter==='issues'?c.status!=='PASS':c.items.some(i=>i.split(':')[0]===selection))),container=$('validation-results');container.replaceChildren();if(!checks.length){container.append(element('div','No issues in this build’s selected checks. Geometry results are not a pressure or manufacturing certification.','pass-message'));return;}const table=element('table',null,'check-table'),head=element('tr');for(const t of ['Status','Rule','Items','Actual','Required'])head.append(element('th',t));table.append(head);for(const c of checks){const row=element('tr');row.title=c.message;row.append(element('td',c.status,c.status),element('td',c.rule),element('td',c.items.join(' ↔ ')),element('td',`${c.actual} ${c.unit}`),element('td',String(c.required)));row.onclick=()=>select(c.items[0].split(':')[0]);table.append(row);}container.append(table);}
async function load(key=state?.project_id){if(!key)return;const preserveView=key===state?.project_id&&!document.body.classList.contains('home');const epoch=++projectEpoch;previews.cancel();lastUsablePreview=null;exactPreview=null;const next=await api('/api/projects/'+key);let nr,nm,nd,reviewError;if(next.build)[nr,nm,nd]=await Promise.all(['validation.json','review.json','resolved_design.json'].map(n=>api(`/api/artifacts/${next.build.build_id}/${n}`).catch(()=>null)));if(epoch!==projectEpoch)return;if(nm?.geometry_kind==='unavailable'){reviewError=nm.review_error;nm=null;}state=next;const networkLabel=document.querySelector('.local-dot');networkLabel.textContent=next.network?.mode==='lan'?'LAN workspace':'Local workspace';networkLabel.title=(next.network?.urls||[]).join('\n');draft=hydrateDesign(structuredClone(next.design),next.engineering?.definitions);report=nr;model=next.stale?null:nm;resolved=next.stale?draft:hydrateDesign(nd||draft,next.engineering?.definitions);viewer?.setReferences(resolved.features);dirty=false;externalChange=false;previews.cancel();if(!model){viewer?.preview(draft);lastUsablePreview={design:cloneDesign(draft)};}if(model){lastUsablePreview={model,design:resolved};viewer?.load(model,resolved.features);previewState('authoritative',`AUTHORITATIVE SAVE & VALIDATE · ${next.build.status} · EXACT OCCT BREP · ${(model.volume_mm3/1000).toFixed(1)} cm³`);}viewer?.setDesign(draft);document.body.classList.remove('home');if(!preserveView)viewer?.fit($('face-view').value);if(!model)refreshPreview();if(!dragStart)requestSolid();renderTree();select(selection);renderReport();renderHeader();notice(reviewError&&!state.stale?reviewError+' Authoritative Save & Validate: '+state.build.status:state.stale?'Project is newer than this build. Save & Validate to update.':'Select a cavity, external port, or hydraulic route.');}
async function build(){if(busy||!state)return;if(!state.project_id){try{await saveProject();}catch(e){notice(e.message,true);return;}}if(busy)return;busy=true;previews.cancel();document.body.classList.add('busy');viewer?.editing(false);for(const e of document.querySelectorAll('button,input,select'))e.disabled=true;renderHeader();notice('Running exact cuts, connectivity, wall checks and STEP round trip…');try{await post('/api/build',{expected_revision:state.revision,design:dirty?draft:null,project_id:state.project_id});await load();history=[];future=[];}catch(e){notice(e.message,true);}finally{busy=false;viewer?.editing(true);document.body.classList.remove('busy');for(const e of document.querySelectorAll('button,input,select'))e.disabled=false;renderHeader();}}
$('build').onclick=build;$('select-block').onclick=()=>select('block');$('reload').onclick=async()=>{if(dirty&&!confirm('Discard unsaved draft and reload?'))return;try{await load();history=[];future=[];renderHeader();}catch(e){notice(e.message,true);}};$('undo').onclick=()=>{if(history.length){future.push(cloneDesign(draft));draft=history.pop();markDirty();renderTree();select(selection);}};$('redo').onclick=()=>{if(future.length){history.push(cloneDesign(draft));draft=future.pop();markDirty();renderTree();select(selection);}};
$('fit').onclick=()=>viewer?.fit($('face-view').value);$('face-view').onchange=e=>viewer?.fit(e.target.value);for(const mode of ['review','solid','void','features'])$(mode+'-mode').onclick=()=>{viewMode=mode;viewer?.mode(mode);requestLayer(mode);for(const key of ['review','solid','void','features'])$(key+'-mode').classList.toggle('active',mode===key);};$('opacity').oninput=e=>{viewer?.opacity(Number(e.target.value)/100);$('opacity-value').textContent=e.target.value+'%';};for(const key of ['cavities','ports','closures','zones','drillings','labels'])$('show-'+key).onchange=e=>viewer?.toggle(key,e.target.checked);$('show-xray').onchange=e=>viewer?.xray(e.target.checked);$('report-filter').onchange=()=>{renderReport();renderHeader();};$('json-open').onclick=()=>{$('json-editor').value=JSON.stringify(draft,null,2);$('json-error').textContent='';$('json-dialog').showModal();};$('json-close').onclick=()=>$('json-dialog').close();$('json-apply').onclick=async()=>{try{const value=await post('/api/check-design',JSON.parse($('json-editor').value));change(()=>draft=hydrateDesign(value,draft.library));$('json-dialog').close();}catch(e){$('json-error').textContent=e.message;}};
async function persistProject(){
  const epoch=projectEpoch,signature=JSON.stringify(draft),key=state?.project_id||null,expected=state?.revision;
  const result=await post('/api/projects',{design:draft,project_id:key,expected_revision:key?expected:null});
  if(epoch!==projectEpoch||(state?.project_id||null)!==key)throw Error('Saved the previous project; another project is now open.');
  state=result;dirty=JSON.stringify(draft)!==signature;externalChange=false;
  if(!dirty){history=[];future=[];}renderHeader();notice(dirty?'Saved the submitted version; newer draft edits still need saving.':'Saved to Projects. Geometry validation is independent of saving.');return result;
}
async function saveProject(){if(savePending)return savePending;$('save-project').disabled=true;savePending=persistProject();try{return await savePending;}finally{savePending=null;$('save-project').disabled=busy;}}
$('save-project').onclick=()=>saveProject().catch(e=>notice(e.message,true));
$('drawings-open').onclick=async()=>{try{if(!state?.project_id||dirty)await saveProject();location.href='/drawing.html?project='+state.project_id;}catch(e){notice(e.message,true);}};
function newProject(value,definitions={}){if(busy)return false;if(dirty&&!confirm('Discard the current unsaved draft and start this project?'))return false;++projectEpoch;draft=hydrateDesign(structuredClone(value),definitions);state={design:draft,revision:'0'.repeat(64),build:null,stale:true};report=null;model=null;resolved=draft;viewer?.setReferences(draft.features);history=[];future=[];selection='block';previews.cancel();lastUsablePreview=null;exactPreview=null;solidStatus();viewMode='review';viewer?.mode('review');$('review-mode').classList.add('active');for(const key of ['solid','void','features'])$(key+'-mode').classList.remove('active');document.body.classList.remove('home');renderReport();markDirty();renderTree();select('block');viewer?.fit();return true;}
const workflowHandlers=workflows({newProject,adoptRoute,$,element,field,action,api,post,get:()=>draft,state:()=>state,change,set:value=>{draft=hydrateDesign(value,draft?.library||[]);},newId,select,notice,resolved:()=>resolved});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});setInterval(async()=>{if(!state?.project_id||busy||document.body.classList.contains('home')||document.hidden||document.querySelector('dialog[open]'))return;try{const next=await api('/api/projects/'+state.project_id);if(next.revision!==state.revision||next.build?.build_id!==state.build?.build_id||next.stale!==state.stale){if(!dirty)await load();else{externalChange=true;renderHeader();notice('Project changed on disk. Draft preserved; reload before saving.',true);}}}catch(e){externalChange=true;renderHeader();notice('Local service unavailable: '+e.message,true);}},5000);const hub=projectLibrary({onDeleted:id=>{if(state?.project_id===id){++projectEpoch;previews.cancel();lastUsablePreview=null;draft=null;state=null;dirty=false;}},$,element,action,api,post,openProject:load,isDirty:()=>dirty,hasProject:()=>!!draft});hub.show();

const requestedProject=new URLSearchParams(location.search).get("project");
if(/^[0-9a-f]{32}$/.test(requestedProject||""))load(requestedProject).catch(e=>notice(e.message,true));
