import './style.css';
import {createViewer} from './viewer.js';
import {clamp,syncNets} from './kinematics.js';
import {pose,axes} from './kinematics.js';
import {workflows} from './workflows.js';
const $=id=>document.getElementById(id),colors={P:'#ef5959',T:'#459cff',A:'#41ca8b',B:'#f2d454'},faces=Object.fromEntries(['top','bottom','front','back','left','right'].map(f=>[f,f]));
let viewMode='review',solidRunning=false,solidWanted=null,solidCache=null;
let state,draft,report,model,resolved,selection='block',dirty=false,busy=false,externalChange=false,viewer,history=[],future=[],previewToken=0,previewTimer,dragStart;
function element(tag,text,cls){const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;}
function notice(message,error=false){$('notice').textContent=message;$('notice').className=error?'error':'';}
async function api(url,options={}){const r=await fetch(url,options);if(!r.ok){const b=await r.json().catch(()=>({}));throw Error(typeof b.detail==='string'?b.detail:JSON.stringify(b.detail||r.status));}return r.json();}
const post=(url,body)=>api(url,{method:'POST',headers:{'Content-Type':'application/json','X-PMC-Request':'local-console'},body:JSON.stringify(body)});
function change(fn){if(busy)return false;const before=structuredClone(draft);try{fn();syncNets(draft);history.push(before);if(history.length>40)history.shift();future=[];markDirty();renderTree();select(selection);return true;}catch(e){draft=before;notice(e.message,true);select(selection);return false;}}
function showSolid(result){viewer?.load(result.model,result.features);viewer?.setDesign(draft);$('model-info').textContent='MACHINED BREP DRAFT · NOT VALIDATED';}
async function requestSolid(){
  if(viewMode!=='solid'||!draft)return;
  if(!dirty&&!state?.stale&&model){viewer?.load(model,resolved.features);viewer?.setDesign(draft);$('model-info').textContent='EXACT MACHINED BREP · SAVED BUILD';return;}
  const signature=JSON.stringify(draft);
  if(solidCache?.signature===signature){showSolid(solidCache.result);return;}
  solidWanted={signature,design:structuredClone(draft)};
  $('model-info').textContent='Computing machined draft…';
  if(solidRunning)return;
  solidRunning=true;
  try{while(solidWanted&&viewMode==='solid'){
    const request=solidWanted;solidWanted=null;
    try{const result=await post('/api/preview-solid',request.design);solidCache={signature:request.signature,result};if(viewMode==='solid'&&JSON.stringify(draft)===request.signature)showSolid(result);}
    catch(e){if(viewMode==='solid'&&JSON.stringify(draft)===request.signature){$('model-info').textContent='MACHINED PREVIEW UNAVAILABLE';notice(e.message,true);}}
  }}finally{solidRunning=false;}
}
function refreshPreview(){const token=++previewToken;clearTimeout(previewTimer);viewer?.preview(draft);viewer?.setDesign(draft);$('model-info').textContent='PARAMETRIC PREVIEW · NOT VALIDATED';previewTimer=setTimeout(async()=>{try{const p=await post('/api/preview',draft);if(token!==previewToken||busy)return;resolved=p.design;viewer?.preview(resolved);viewer?.setDesign(draft);$('model-info').textContent='UNVALIDATED · '+p.routes.map(r=>`${r.net}: ${r.drillings} drills / ${r.plugs} plugs`).join(' · ');if(viewMode==='solid')requestSolid();}catch(e){if(token===previewToken)notice('Preview: '+e.message,true);}},100);}
function markDirty(){dirty=true;renderHeader();refreshPreview();notice('Draft preview updated. Save & Validate runs exact geometry checks and writes an immutable build.');}
try{viewer=createViewer($('viewport'),select,(id,u,v,done)=>{if(busy)return;const f=draft.features.find(f=>f.id===id);if(!dragStart)dragStart=structuredClone(draft);f.u=u;f.v=v;dirty=true;renderHeader();refreshPreview();$('selection-label').textContent=`${id} · ${f.face} · U ${u.toFixed(1)} / V ${v.toFixed(1)} mm`;notice('Live position · envelope clamped to face · 1 mm snap · preview is not validated');if(done){history.push(dragStart);future=[];dragStart=null;select(id);}});}catch(e){notice('WebGL: '+e.message,true);}
function renderHeader(){if(!draft)return;$('review-open').textContent='Engineering Review · '+((draft.review_items||[]).filter(r=>r.status==='open').length+draft.components.filter(c=>c.status==='unconfirmed').length+draft.library.filter(d=>d.native&&draft.features.some(f=>!f.suppressed&&f.definition===d.id)).reduce((n,d)=>n+(d.native.geometry_status==='draft-projection'?1:0)+(d.native.machining_status==='unresolved'?1:0),0));$('project-name').textContent=draft.name;const b=draft.block;$('dimensions').textContent=`${b.length} × ${b.width} × ${b.height} mm`;$('revision').textContent='SHA '+state.revision.slice(0,8);const status=dirty?'DRAFT':externalChange||state.stale?'STALE':state.build?.status||'UNBUILT';$('status').textContent=status;$('status').className='badge '+(status==='FAIL'?'fail':status==='PASS'?'':'warning');for(const [id,name]of [['step-download','production.step'],['data-download','design.json'],['report-download','validation.md'],['chart-download','drill-chart.csv'],['manufacturing-download','manufacturing.json']]){const ok=!!state.build&&!dirty&&!state.stale&&!externalChange&&!busy&&(id!=='step-download'||status==='PASS');$(id).classList.toggle('disabled',!ok);if(ok)$(id).href=`/api/artifacts/${state.build.build_id}/${name}`;else $(id).removeAttribute('href');}$('build').textContent=busy?'Computing exact solids…':'Save & Validate';$('undo').disabled=busy||!history.length;$('redo').disabled=busy||!future.length;if(dirty||state.stale)$('check-counts').textContent='Previous build results · draft not validated';}
function renderTree(){const tree=$('feature-tree');tree.replaceChildren();$('feature-count').textContent=draft.features.length+' ITEMS';for(const kind of ['cavity','port','drilling']){const group=element('div',null,'tree-group'),list=draft.features.filter(f=>f.kind===kind);group.append(element('div',`${{cavity:'Cartridges',port:'External ports',drilling:'Manual drillings'}[kind]} / ${list.length}`,'tree-heading'));for(const f of list){const btn=element('button',null,'tree-feature');btn.dataset.feature=f.id;const dot=element('span',null,'swatch');dot.style.background=colors[f.circuit]||'#b4c7da';btn.append(dot,element('span',f.id),element('small',f.suppressed?'SUPPRESSED':f.kind==='cavity'?Object.values(f.circuits).join(' / '):f.face));btn.onclick=()=>select(f.id);group.append(btn);}tree.append(group);}if(draft.nets.some(n=>n.routing==='automatic'))tree.append(element('p','Generated drillings follow Hydraulic Nets.','inspector-note'));$('circuits').replaceChildren();for(const n of draft.nets){const btn=element('button',n.id,'circuit-toggle');btn.style.borderColor=n.color||colors[n.id]||'#b08bea';btn.onclick=()=>{btn.classList.toggle('off');viewer.circuit(n.id,!btn.classList.contains('off'));};$('circuits').append(btn);}}
function field(parent,label,value,onChange,options=null,numeric=false){const wrap=element('label',label,'field'),input=document.createElement(options?'select':'input');input.setAttribute('aria-label',label);if(options)for(const [key,text]of Object.entries(options)){const o=element('option',text);o.value=key;input.append(o);}else{input.type=numeric?'number':'text';if(numeric)input.step='.1';}input.value=value??'';input.onchange=()=>{const v=numeric?input.valueAsNumber:input.value;if(numeric&&!Number.isFinite(v)){input.reportValidity();return;}onChange(v);};wrap.append(input);parent.append(wrap);return input;}
const prop=(p,l,v,fn,o=null,n=false)=>field(p,l,v,x=>change(()=>fn(x)),o,n);
function action(parent,label,fn){const b=element('button',label);b.type='button';b.onclick=fn;parent.append(b);return b;}
function newId(prefix){let i=1;while(draft.features.some(f=>f.id===prefix+i))i++;return prefix+i;}
function replaceCavity(f,id){
  const def=draft.library.find(d=>d.id===id),mapping=Object.fromEntries(def.zones.map(z=>[z.id,f.circuits[z.id]||'']));
  const apply=()=>change(()=>{if(Object.values(mapping).some(n=>!n))throw Error('Choose a net for every new interface');f.definition=id;f.circuits={...mapping};[f.u,f.v]=clamp(f,draft,f.u,f.v);const valid=new Set(def.zones.map(z=>`${f.id}:${z.id}`));for(const bore of draft.features)bore.connects_to=bore.connects_to.filter(t=>!t.startsWith(f.id+':')||valid.has(t));for(const c of draft.components)if(c.feature_id===f.id)c.status='unconfirmed';});
  if(def.zones.length===Object.keys(f.circuits).length&&Object.values(mapping).every(Boolean)){apply();return;}
  $('workflow-title').textContent='Replace cavity · confirm interface mapping';const box=$('workflow-content');box.replaceChildren(element('p','The new cavity has different hydraulic windows. Assign every new window explicitly. Removed windows will lose their physical contact declarations; schematic mapping must be reviewed.'));
  for(const z of def.zones)field(box,`New interface ${z.id}`,mapping[z.id],v=>mapping[z.id]=v,{'':'Select hydraulic net',...Object.fromEntries(draft.nets.map(n=>[n.id,n.id]))});
  action(box,'Apply replacement',()=>{if(Object.values(mapping).some(n=>!n)){$('workflow-error').textContent='Choose a net for every interface';return;}apply();$('workflow-dialog').close();});$('workflow-error').textContent='';$('workflow-dialog').showModal();select(f.id);
}
function remove(id){change(()=>{const ids=new Set([id]);let n;do{n=ids.size;for(const f of draft.features)if(ids.has(f.parent_id))ids.add(f.id);}while(ids.size!==n);draft.features=draft.features.filter(f=>!ids.has(f.id));for(const f of draft.features)f.connects_to=f.connects_to.filter(t=>!ids.has(t.split(':')[0]));for(const c of draft.components)if(ids.has(c.feature_id)){c.feature_id=null;c.status='unconfirmed';}selection='block';});}
function select(id){if(!draft)return;selection=draft.features.some(f=>f.id===id)?id:'block';viewer?.select(selection);$('selection-label').textContent=selection==='block'?'':selection;for(const b of document.querySelectorAll('[data-feature]'))b.classList.toggle('active',b.dataset.feature===selection);$('select-block').classList.toggle('active',selection==='block');const form=$('inspector');form.replaceChildren();form.onsubmit=e=>e.preventDefault();
if(selection==='block'){$('selection-kind').textContent='STOCK';form.append(element('div','MANIFOLD','inspector-title'));prop(form,'Project name',draft.name,v=>draft.name=v);for(const [key,label]of [['length','Length X / mm'],['width','Width Y / mm'],['height','Height Z / mm']])prop(form,label,draft.block[key],v=>draft.block[key]=v,null,true);prop(form,'Material',draft.block.material,v=>draft.block.material=v);prop(form,'Minimum wall / mm',draft.rules.minimum_wall,v=>draft.rules.minimum_wall=v,null,true);prop(form,'Design priority',draft.constraints.priority,v=>draft.constraints.priority=v,{compact:'Compact envelope',fewer_plugs:'Fewer plugs',simple_machining:'Simpler machining',short_drills:'Shorter drillings'});prop(form,'Envelope limit X,Y,Z / mm',(draft.constraints.envelope_max||[]).join(', '),v=>draft.constraints.envelope_max=v.trim()?v.split(',').map(Number):null);prop(form,'Engineering notes',draft.constraints.notes,v=>draft.constraints.notes=v);form.append(element('p','Origin: left / front / bottom. Exact wall and intersection checks run on Save & Validate.','inspector-note'));}
else{const f=draft.features.find(f=>f.id===selection);const p=pose(f,draft.block),uv=axes[f.face];form.append(element('p',`Origin XYZ: ${p.origin.map(x=>x.toFixed(3)).join(', ')} mm · U=+${'XYZ'[uv[0]]}, V=+${'XYZ'[uv[1]]} · inward ${p.direction.join(', ')}`,'property-note'));$('selection-kind').textContent=f.kind.toUpperCase();form.append(element('div',f.id,'inspector-title'));const bar=element('div',null,'action-row');form.append(bar);action(bar,'Duplicate',()=>change(()=>{const copy=structuredClone(f);copy.id=newId(f.kind==='cavity'?'CV':'PORT');copy.parent_id=null;copy.schematic_id='';copy.connects_to=[];[copy.u,copy.v]=clamp(copy,draft,copy.u+25,copy.v+20);draft.features.push(copy);selection=copy.id;}));action(bar,f.suppressed?'Restore':'Suppress',()=>change(()=>f.suppressed=!f.suppressed));action(bar,'Delete',()=>remove(f.id));prop(form,'Face',f.face,v=>{f.face=v;[f.u,f.v]=clamp(f,draft,f.u,f.v);},faces);const row=element('div',null,'field-row');form.append(row);prop(row,'Position U / mm',f.u,v=>{[f.u,f.v]=clamp(f,draft,v,f.v);},null,true);prop(row,'Position V / mm',f.v,v=>{[f.u,f.v]=clamp(f,draft,f.u,v);},null,true);
if(f.kind==='cavity'){field(form,'Replace cavity',f.definition,v=>replaceCavity(f,v),Object.fromEntries(draft.library.map(d=>[d.id,d.label+' · '+d.revision])));prop(form,'Cartridge model',f.cartridge_model,v=>f.cartridge_model=v);for(const key of Object.keys(f.circuits))prop(form,`Interface ${key} → Net`,f.circuits[key],v=>f.circuits[key]=v,Object.fromEntries(draft.nets.map(n=>[n.id,n.id])));const def=draft.library.find(d=>d.id===f.definition);action(form,'Edit pinned definition',()=>workflowHandlers.editDefinition(def));form.append(element('p',`${def.manufacturer} · ${def.provenance}\n${def.source}\n${def.stages.map(s=>`Ø${s.diameter.toFixed(4)} / ${s.start.toFixed(4)}–${s.end.toFixed(4)} mm`).join('\n')}`,'property-note'));}
else{prop(form,'Hydraulic net',f.circuit,v=>f.circuit=v,Object.fromEntries(draft.nets.map(n=>[n.id,n.id])));for(const key of ['diameter','depth'])prop(form,key==='diameter'?'Diameter / mm':'Cylinder depth / mm',f[key],v=>f[key]=v,null,true);if(f.kind==='port')prop(form,'Port specification',f.size,v=>f.size=v);else{prop(form,'Drill direction X,Y,Z (blank = face normal)',(f.direction||[]).join(', '),v=>f.direction=v.trim()?v.split(',').map(Number):null);prop(form,'Entry closure',String(f.plugged),v=>f.plugged=v==='true',{'true':'Plug','false':'Coaxial external port'});prop(form,'Plug engagement / mm',f.plug_length,v=>f.plug_length=v,null,true);prop(form,'Expected contacts',f.connects_to.join(', '),v=>f.connects_to=v.split(',').map(s=>s.trim()).filter(Boolean));}}
const advanced=element('details');advanced.append(element('summary','Relationships & machining'));form.append(advanced);prop(advanced,'Rotation / degrees',f.rotation,v=>f.rotation=v,null,true);prop(advanced,'Parent feature',f.parent_id||'',v=>{f.parent_id=v||null;const p=draft.features.find(x=>x.id===v);if(p)f.local_offset=[f.u-p.u,f.v-p.v];},{'':'Independent',...Object.fromEntries(draft.features.filter(x=>x.id!==f.id).map(x=>[x.id,x.id]))});prop(advanced,'Machining ID',f.machining_id,v=>f.machining_id=v);advanced.append(element('p','Rotation moves attached offsets and native footprint cuts.','inspector-note'));for(const [n,t]of Object.entries(report?.graph||{}).filter(([n])=>n===f.id||n.startsWith(f.id+':')))form.append(element('div',`${n} → ${t.join(', ')||'Disconnected'} (last build)`,'property-note'));}
$('feature-results').replaceChildren();for(const c of (report?.checks||[]).filter(c=>c.status!=='PASS'&&c.items.some(i=>i.split(':')[0]===selection)))$('feature-results').append(element('div',`${c.status} · ${c.rule}: ${c.actual} / ${c.required} ${c.unit}`,'feature-check'));if($('report-filter').value==='selected')renderReport();}
function renderReport(){if(!report)return;$('check-counts').textContent=`${report.counts.PASS} PASS / ${report.counts.WARNING} WARNING / ${report.counts.FAIL} FAIL`;$('build-time').textContent=new Date(report.generated_at).toLocaleTimeString();$('limitations').replaceChildren(...report.limitations.map(s=>element('li',s)));const filter=$('report-filter').value,checks=report.checks.filter(c=>filter==='all'||(filter==='issues'?c.status!=='PASS':c.items.some(i=>i.split(':')[0]===selection))),container=$('validation-results');container.replaceChildren();if(!checks.length){container.append(element('div','No issues in this build’s selected checks. Geometry results are not a pressure or manufacturing certification.','pass-message'));return;}const table=element('table',null,'check-table'),head=element('tr');for(const t of ['Status','Rule','Items','Actual','Required'])head.append(element('th',t));table.append(head);for(const c of checks){const row=element('tr');row.title=c.message;row.append(element('td',c.status,c.status),element('td',c.rule),element('td',c.items.join(' ↔ ')),element('td',`${c.actual} ${c.unit}`),element('td',String(c.required)));row.onclick=()=>select(c.items[0].split(':')[0]);table.append(row);}container.append(table);}
async function load(){const next=await api('/api/state');let nr,nm,nd;if(next.build)[nr,nm,nd]=await Promise.all(['validation.json','review.json','resolved_design.json'].map(n=>api(`/api/artifacts/${next.build.build_id}/${n}`).catch(()=>null)));state=next;const networkLabel=document.querySelector('.local-dot');networkLabel.textContent=next.network?.mode==='lan'?'LAN · No cloud':'Local · No cloud';networkLabel.title=(next.network?.urls||[]).join('\n');draft=structuredClone(next.design);report=nr;model=nm;resolved=nd||draft;dirty=false;externalChange=false;++previewToken;clearTimeout(previewTimer);if(model){viewer?.load(model,resolved.features);$('model-info').textContent=`EXACT OCCT BREP · ${(model.volume_mm3/1000).toFixed(1)} cm³`;}viewer?.setDesign(draft);renderTree();select(selection);renderReport();renderHeader();notice(state.stale?'Project is newer than this build. Save & Validate to update.':'Select a component or drag its green ring. Start with a schematic or the cavity library.');}
async function build(){if(busy||!state)return;busy=true;++previewToken;clearTimeout(previewTimer);document.body.classList.add('busy');viewer?.editing(false);for(const e of document.querySelectorAll('button,input,select'))e.disabled=true;renderHeader();notice('Running exact cuts, connectivity, wall checks and STEP round trip…');try{await post('/api/build',{expected_revision:state.revision,design:dirty?draft:null});await load();history=[];future=[];}catch(e){notice(e.message,true);}finally{busy=false;viewer?.editing(true);document.body.classList.remove('busy');for(const e of document.querySelectorAll('button,input,select'))e.disabled=false;renderHeader();}}
$('build').onclick=build;$('select-block').onclick=()=>select('block');$('reload').onclick=async()=>{if(dirty&&!confirm('Discard unsaved draft and reload?'))return;try{await load();history=[];future=[];renderHeader();}catch(e){notice(e.message,true);}};$('undo').onclick=()=>{if(history.length){future.push(structuredClone(draft));draft=history.pop();markDirty();renderTree();select(selection);}};$('redo').onclick=()=>{if(future.length){history.push(structuredClone(draft));draft=future.pop();markDirty();renderTree();select(selection);}};
$('fit').onclick=()=>viewer?.fit($('face-view').value);$('face-view').onchange=e=>viewer?.fit(e.target.value);for(const mode of ['review','solid'])$(mode+'-mode').onclick=()=>{viewMode=mode;viewer?.mode(mode);if(mode==='solid')requestSolid();else solidWanted=null;$('review-mode').classList.toggle('active',mode==='review');$('solid-mode').classList.toggle('active',mode==='solid');};$('opacity').oninput=e=>{viewer?.opacity(Number(e.target.value)/100);$('opacity-value').textContent=e.target.value+'%';};for(const key of ['cavities','zones','drillings','labels'])$('show-'+key).onchange=e=>viewer?.toggle(key,e.target.checked);$('report-filter').onchange=()=>{renderReport();renderHeader();};$('json-open').onclick=()=>{$('json-editor').value=JSON.stringify(draft,null,2);$('json-error').textContent='';$('json-dialog').showModal();};$('json-close').onclick=()=>$('json-dialog').close();$('json-apply').onclick=async()=>{try{const value=await post('/api/check-design',JSON.parse($('json-editor').value));change(()=>draft=value);$('json-dialog').close();}catch(e){$('json-error').textContent=e.message;}};
const workflowHandlers=workflows({$,element,field,action,api,post,get:()=>draft,state:()=>state,change,set:value=>{draft=value;},newId,select,notice,resolved:()=>resolved});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});setInterval(async()=>{if(!state||busy||document.hidden||document.querySelector('dialog[open]'))return;try{const next=await api('/api/state');if(next.revision!==state.revision||next.build?.build_id!==state.build?.build_id||next.stale!==state.stale){if(!dirty)await load();else{externalChange=true;renderHeader();notice('Project changed on disk. Draft preserved; reload before saving.',true);}}}catch(e){externalChange=true;renderHeader();notice('Local service unavailable: '+e.message,true);}},5000);load().catch(e=>notice(e.message,true));
