import {clamp,syncNets} from './kinematics.js';
export function workflows(ctx){
const {$,element,field,action,api,post,get,state,change,set,newId,select,notice,resolved}=ctx;
const content=$('workflow-content'),dialog=$('workflow-dialog');
const guard=fn=>async()=>{try{await fn();$('workflow-error').textContent='';}catch(e){$('workflow-error').textContent=e.message;}};
function open(title){$('workflow-title').textContent=title;content.replaceChildren();$('workflow-error').textContent='';if(!dialog.open)dialog.showModal();}
$('workflow-close').onclick=()=>dialog.close();
function insert(def,face='top'){
  change(()=>{const d=get(),existing=d.library.find(x=>x.id===def.id);if(existing&&JSON.stringify(existing)!==JSON.stringify(def))throw Error('This project pins another revision with this ID. Save a new library ID to use both revisions.');if(!existing)d.library.push(structuredClone(def));const f={id:newId('CV'),kind:'cavity',face,u:d.block.length/2,v:d.block.width/2,definition:def.id,circuits:Object.fromEntries(def.zones.map((z,i)=>[z.id,d.nets[i%d.nets.length]?.id||'P'])),connects_to:[],suppressed:false,rotation:0,cartridge_model:def.cartridge_models[0]||'',schematic_id:'',parent_id:null,local_offset:[0,0],machining_id:''};[f.u,f.v]=clamp(f,d,f.u,f.v);d.features.push(f);syncNets(d);select(f.id);});dialog.close();
}
function editor(source){
  const def=structuredClone(source);open('Cavity definition · reusable local revision');
  const grid=element('div',null,'editor-grid');content.append(grid);
  for(const [key,label]of [['id','Definition ID'],['label','Label'],['manufacturer','Manufacturer'],['revision','Revision'],['valve_function','Valve function'],['source','Drawing / source reference'],['thread_note','Thread / tolerance notes'],['machining_notes','Machining notes']])field(grid,label,def[key],v=>def[key]=v);
  field(grid,'Cartridge models (comma separated)',def.cartridge_models.join(', '),v=>def.cartridge_models=v.split(',').map(s=>s.trim()).filter(Boolean));
  field(grid,'Provenance',def.provenance,v=>{def.provenance=v;def.demo_only=v==='demo';},{demo:'Demo dimensions',candidate:'Candidate · requires drawing review','drawing-verified':'Drawing verified by engineer'});
  field(grid,'Service envelope diameter / mm',def.clearance_diameter,v=>def.clearance_diameter=v,null,true);field(grid,'Service envelope height / mm',def.clearance_height,v=>def.clearance_height=v,null,true);
  function rows(key){const box=element('section',null,'definition-section');box.append(element('h3',key==='stages'?'Cutting stages':'Installed hydraulic interface windows'));const holder=element('div');box.append(holder);content.append(box);function draw(){holder.replaceChildren();for(const [i,s]of def[key].entries()){const row=element('div',null,'editor-grid');holder.append(row);if(key==='zones')field(row,`Window ${i+1} ID`,s.id,v=>s.id=v);for(const k of ['start','end','diameter'])field(row,`${key} ${i+1} ${k}`,s[k],v=>s[k]=v,null,true);action(row,'Remove row',()=>{def[key].splice(i,1);draw();});}}draw();action(box,'Add '+(key==='stages'?'stage':'interface'),()=>{const end=def[key].at(-1)?.end||0;def[key].push({...(key==='zones'?{id:'zone'+(def[key].length+1)}:{}),start:end,end:end+10,diameter:10});draw();});}
  rows('stages');rows('zones');content.append(element('p','Saving validates contiguous cutting stages and contained hydraulic windows. Existing project definitions remain pinned. Vendor approval is never inferred.'));
  action(content,'Save library revision',guard(async()=>{await post('/api/library',def);await library();}));
}
async function library(){open('Cavity Library');const entries=await api('/api/library');const search=element('input');search.placeholder='Search manufacturer, cartridge, cavity or function';search.setAttribute('aria-label','Search cavity library');content.append(search);const list=element('div',null,'library-list');content.append(list);const render=()=>{list.replaceChildren();for(const item of entries.filter(x=>JSON.stringify(x.definition).toLowerCase().includes(search.value.toLowerCase()))){const d=item.definition,card=element('div',null,'library-card');card.append(element('h3',d.label),element('p',`${d.manufacturer} · ${d.id} · revision ${d.revision}\n${d.valve_function} · ${d.cartridge_models.join(', ')||'Model unconfirmed'}\n${d.provenance} · ${d.stages.length} stages / ${d.zones.length} interfaces`));action(card,'Insert cavity',()=>insert(d));action(card,'Edit / create revision',()=>editor(d));list.append(card);}};search.oninput=render;render();action(content,'New definition from template',()=>{const d=structuredClone(entries[0].definition);d.id='CUSTOM_CAVITY';d.label='New cavity';d.provenance='candidate';d.demo_only=false;editor(d);});}
$('library-open').onclick=guard(library);
$('add-port').onclick=()=>{change(()=>{const d=get(),f={id:newId('PORT'),kind:'port',face:'front',u:d.block.length/2,v:d.block.height/2,circuit:d.nets[0]?.id||'P',diameter:12,depth:12,tip_angle:118,clearance_diameter:20,clearance_height:20,connects_to:[],suppressed:false,rotation:0,parent_id:null,local_offset:[0,0],machining_id:'',size:'Custom',port_type:'Demo straight bore',plugged:false,plug_length:8};[f.u,f.v]=clamp(f,d,f.u,f.v);d.features.push(f);select(f.id);});};
function nets(){open('Hydraulic Nets · intent and derived connections');content.append(element('p','Automatic routes connect declared interfaces with orthogonal face drillings. Route length and plug count rank candidates; exact validation decides whether a route is acceptable.'));
  action(content,'Adopt automatic routing (replace manual drillings)',guard(async()=>{const d=await post('/api/adopt-routing',get());change(()=>set(d));nets();}));
  const newNet=element('div',null,'action-row'),name=element('input');name.setAttribute('aria-label','New net ID');name.placeholder='NET_P';newNet.append(name);action(newNet,'Add net',()=>{if(!/^[A-Za-z][A-Za-z0-9_-]{0,39}$/.test(name.value)||get().nets.some(n=>n.id===name.value)){$('workflow-error').textContent='Use a unique engineering ID';return;}change(()=>get().nets.push({id:name.value,label:name.value,members:[],routing:'automatic',diameter:8}));nets();});content.append(newNet);
  for(const n of get().nets){const card=element('section',null,'library-card');content.append(card);card.append(element('h3',n.id),element('p',n.members.join(' ↔ ')||'No interfaces assigned'));const edit=(label,value,fn,o=null,num=false)=>field(card,label,value,v=>change(()=>fn(v)),o,num);
    edit('Routing · '+n.id,n.routing,v=>n.routing=v,{manual:'Manual geometry',automatic:'Automatic from intent'});edit('Drill diameter · '+n.id,n.diameter,v=>n.diameter=v,null,true);edit('First routing axis · '+n.id,n.preferred_axis||'auto',v=>n.preferred_axis=v,{auto:'Compare all axes',x:'X',y:'Y',z:'Z'});edit('Entry preference · '+n.id,n.entry_preference||'nearest',v=>n.entry_preference=v,{nearest:'Nearest / reuse port',negative:'Negative face',positive:'Positive face'});edit('Flow L/min · '+n.id,n.flow_lpm,v=>n.flow_lpm=v,null,true);edit('Pressure bar · '+n.id,n.pressure_bar,v=>n.pressure_bar=v,null,true);
    if(n.routing==='automatic')action(card,'Freeze '+n.id+' geometry for manual override',guard(async()=>{const d=await post('/api/freeze-net',{design:get(),net:n.id});change(()=>set(d));nets();}));
  }
  const route=resolved();if(route){const details=element('details');details.append(element('summary','Inspect generated drilling coordinates'));for(const f of route.features.filter(f=>f.route_net))details.append(element('p',`${f.id} · ${f.route_net} · ${f.face} U${f.u.toFixed(2)} V${f.v.toFixed(2)} · Ø${f.diameter} × ${f.depth.toFixed(2)} · ${f.plugged?'plug':'external port'}`));content.append(details);}
}
$('nets-open').onclick=nets;
function schematic(){open('Schematic → Codex → Manifold');content.append(element('p','Upload a local PDF, PNG or JPEG. Prepare a handoff, then paste its prompt into this Codex task. Codex reads the actual file and proposes the same editable project objects used here.'));
  const input=element('input');input.type='file';input.accept='.pdf,.png,.jpg,.jpeg';input.setAttribute('aria-label','Upload schematic');content.append(input);input.onchange=guard(async()=>{const f=input.files[0];if(!f)return;const asset=await api('/api/assets',{method:'POST',headers:{'Content-Type':f.type,'X-PMC-Request':'local-console','X-File-Name':encodeURIComponent(f.name)},body:f});change(()=>{if(!get().schematics.some(a=>a.sha256===asset.sha256))get().schematics.push(asset);});schematic();});
  for(const a of get().schematics){const card=element('div',null,'library-card');card.append(element('h3',a.name));const link=element('a','Open local asset');link.href='/api/assets/'+a.sha256;link.target='_blank';link.rel='noopener';card.append(link,element('p','SHA-256 '+a.sha256));if(a.media_type.startsWith('image/')){const img=element('img');img.src=link.href;img.alt=a.name;img.className='schematic-preview';card.append(img);}content.append(card);}
  const components=element('section');components.append(element('h3','Schematic component mapping'));content.append(components);
  for(const c of get().components){const row=element('div',null,'library-card');row.append(element('strong',c.id+' · '+c.function));field(row,'Placed feature · '+c.id,c.feature_id||'',v=>change(()=>{c.feature_id=v||null;}),{'':'Not placed',...Object.fromEntries(get().features.filter(f=>f.kind==='cavity').map(f=>[f.id,f.id]))});field(row,'Confirmation · '+c.id,c.status,v=>change(()=>c.status=v),{unconfirmed:'Unconfirmed',confirmed:'Confirmed by engineer'});row.append(element('p',JSON.stringify(c.ports)));components.append(row);}
  action(components,'Map placed cartridges as schematic components',()=>{change(()=>{for(const f of get().features.filter(f=>f.kind==='cavity'))if(!get().components.some(c=>c.feature_id===f.id))get().components.push({id:f.id,label:f.id,function:'Requires schematic review',cartridge_model:f.cartridge_model,cavity_definition:f.definition,ports:{...f.circuits},feature_id:f.id,status:'unconfirmed'});});schematic();});
  action(content,'Design with Codex · prepare handoff',guard(async()=>{const h=await post('/api/handoff',{expected_revision:state().revision,design:get()});const box=element('div',null,'library-card');box.append(element('h3','Ready for Codex · awaiting agent'),element('p',h.message));const text=element('textarea');text.value=h.prompt;text.readOnly=true;text.setAttribute('aria-label','Codex handoff prompt');box.append(text);action(box,'Copy Codex prompt',guard(async()=>{await navigator.clipboard.writeText(h.prompt);notice('Handoff prompt copied. Paste it into the current Codex task.');}));content.append(box);}));
}
$('schematic-open').onclick=schematic;
}
