import {libraryUI,structuredFields} from './library-ui.js';
import {projectUI} from './project-ui.js';
import {clamp,syncNets} from './kinematics.js';
export function workflows(ctx){
const {$,element,field,action,api,post,get,state,change,set,newId,select,notice,resolved}=ctx;
const content=$('workflow-content'),dialog=$('workflow-dialog');
const guard=fn=>async()=>{try{await fn();$('workflow-error').textContent='';}catch(e){$('workflow-error').textContent=e.message;}};
function open(title){$('workflow-title').textContent=title;content.replaceChildren();$('workflow-error').textContent='';if(!dialog.open)dialog.showModal();}
$('workflow-close').onclick=()=>dialog.close();
function insert(def,face='top'){
  def=structuredClone(def);const ok=change(()=>{const d=get();let existing=d.library.find(x=>x.id===def.id);if(existing&&JSON.stringify(existing)!==JSON.stringify(def)){def.catalog_id=def.catalog_id||def.id;def.id=def.id.slice(0,27)+'_r'+Date.now().toString(36);existing=null;}if(!existing)d.library.push(structuredClone(def));const f={id:newId('CV'),kind:'cavity',face,u:d.block.length/2,v:d.block.width/2,definition:def.id,circuits:Object.fromEntries(def.zones.map((z,i)=>[z.id,d.nets[i%d.nets.length]?.id||'P'])),connects_to:[],suppressed:false,rotation:0,cartridge_model:def.cartridge_models[0]||'',schematic_id:'',parent_id:null,local_offset:[0,0],machining_id:''};[f.u,f.v]=clamp(f,d,f.u,f.v);d.features.push(f);if(def.native){d.review_items??=[];d.review_items.push({id:'MAP_'+f.id+'_'+Date.now().toString(36),kind:'connection',subject:f.id,description:'Review the imported cavity interface-to-net assignments and installation envelope.',proposed_value:Object.entries(f.circuits).map(([p,n])=>p+' → '+n).join(', '),severity:'review',status:'open',resolution:''});}syncNets(d);select(f.id);});if(ok)dialog.close();else $('workflow-error').textContent=$('notice').textContent;
}
function editor(source,projectScope=false){
  const def=structuredClone(source);if(def.native)def.native.derived_from=def.native.record.id+'@'+def.native.source_sha256;if(def.native)def.revision='PMC-'+(Number(/^PMC-(\d+)$/.exec(def.revision)?.[1]||0)+1);open(projectScope?'Cavity definition · current project':'Cavity definition · reusable local revision');
  const grid=element('div',null,'editor-grid');content.append(grid);
  for(const [key,label]of [['id','Definition ID'],['label','Label'],['manufacturer','Manufacturer'],['revision','Revision'],['valve_function','Valve function'],['source','Drawing / source reference'],['thread_note','Thread / tolerance notes'],['machining_notes','Machining notes']]){if(projectScope&&key==='id'){grid.append(element('p','Pinned ID: '+def.id));continue;}field(grid,label,def[key],v=>def[key]=v);}
  field(grid,'Cartridge models (comma separated)',def.cartridge_models.join(', '),v=>def.cartridge_models=v.split(',').map(s=>s.trim()).filter(Boolean));
  field(grid,'Provenance',def.provenance,v=>{def.provenance=v;def.demo_only=v==='demo';},{demo:'Demo dimensions',candidate:'Candidate · requires drawing review','drawing-verified':'Drawing verified by engineer'});
  field(grid,'Service envelope diameter / mm',def.clearance_diameter,v=>def.clearance_diameter=v,null,true);field(grid,'Service envelope height / mm',def.clearance_height,v=>def.clearance_height=v,null,true);
  function rows(key){const box=element('section',null,'definition-section');box.append(element('h3',key==='stages'?'Cutting stages':'Installed hydraulic interface windows'));const holder=element('div');box.append(holder);content.append(box);function draw(){holder.replaceChildren();for(const [i,s]of def[key].entries()){const row=element('div',null,'editor-grid');holder.append(row);if(key==='zones'){field(row,`Window ${i+1} ID`,s.id,v=>s.id=v);field(row,`Window ${i+1} offset U`,s.offset_u||0,v=>s.offset_u=v,null,true);field(row,`Window ${i+1} offset V`,s.offset_v||0,v=>s.offset_v=v,null,true);field(row,`Window ${i+1} profile clipping`,String(s.clip_to_cut||false),v=>s.clip_to_cut=v==='true',{'false':'Cylinder window','true':'Clip to exact cut profile'});}for(const k of ['start','end','diameter'])field(row,`${key} ${i+1} ${k}`,s[k],v=>s[k]=v,null,true);action(row,'Remove row',()=>{def[key].splice(i,1);draw();});}}draw();action(box,'Add '+(key==='stages'?'stage':'interface'),()=>{const end=def[key].at(-1)?.end||0;def[key].push({...(key==='zones'?{id:'zone'+(def[key].length+1)}:{}),start:end,end:end+10,diameter:10});draw();});}
  if(def.native){const box=element('section',null,'library-card');content.append(box);box.append(element('h3','Native MDTools record · '+def.native.record.unit_system),element('p',def.native.derived_from?'Source: PMC modified from MDTools 930 · '+def.revision:'Source: Imported from MDTools 930'),element('p','Complete source and footprint records stay pinned. Editing creates a PMC revision; original source files remain unchanged. Geometry projection and machining decisions are independent.'));field(box,'Geometry mapping status',def.native.geometry_status,v=>def.native.geometry_status=v,{'draft-projection':'Draft · mapping review required','imported-dimensional':'Imported dimensional mapping','engineer-mapped':'Mapped by engineer'});field(box,'Geometry decision',def.native.mapping_decision,v=>def.native.mapping_decision=v);field(box,'Depth datum',def.native.datum_mode,v=>def.native.datum_mode=v,{'step0-relative':'Steps 1–11 from Step 0','surface-relative':'Source depths from surface'});field(box,'Machining status',def.native.machining_status,v=>def.native.machining_status=v,{unresolved:'Imported recipe · review required','engineer-reviewed':'Reviewed by engineer'});field(box,'Machining decision',def.native.machining_decision,v=>def.native.machining_decision=v);structuredFields(ctx,box,{record:def.native.record,related_records:def.native.related_records},'Native record',()=>{def.native.geometry_status='draft-projection';def.native.machining_status='unresolved';});action(box,'Rebuild CAD mapping from edited native data',guard(async()=>editor(await post('/api/library/project-native',def),projectScope)));}
  if(def.cutting_primitives?.length){const box=element('details');box.append(element('summary','Derived compatibility envelope · read-only'),element('p',def.stages.map(s=>`Ø${s.diameter.toFixed(4)} / ${s.start.toFixed(4)}–${s.end.toFixed(4)} mm`).join('; ')));content.append(box);}else rows('stages');rows('zones');
  if(def.cutting_primitives?.length){const box=element('section',null,'library-card');box.append(element('h3','Explicit CAD cuts · mm'),element('p','Cylinders, conical seats and annular grooves with local footprint offsets. These operations drive exact CAD; legacy stages remain the compatibility envelope.'));content.append(box);structuredFields(ctx,box,def.cutting_primitives,'CAD cuts');action(box,'Add annular cut',()=>{def.cutting_primitives.push({kind:'annulus',source_ref:'PMC custom groove',start:0,end:2,diameter:20,inner_diameter:16,end_diameter:0,offset_u:0,offset_v:0});editor(def,projectScope);});}content.append(element('p',projectScope?'Apply updates this project’s pinned definition and marks affected component mappings for review. Exact checks run on Save & Validate.':'Saving checks the library schema. Exact mapped-interface checks run on Save & Validate. Existing project definitions remain pinned.'));
  if(projectScope){action(content,'Apply to current project',guard(async()=>{
    const baseline=JSON.stringify(get()),candidate=structuredClone(get());candidate.library[candidate.library.findIndex(x=>x.id===source.id)]=def;
    const affected=candidate.features.filter(f=>f.kind==='cavity'&&f.definition===source.id);
    const apply=async()=>{if(JSON.stringify(get())!==baseline)throw Error('Project changed while editing. Reopen the pinned definition.');for(const f of affected){if(Object.values(f.circuits).some(n=>!n))throw Error('Choose a net for every interface');[f.u,f.v]=clamp(f,candidate,f.u,f.v);const valid=new Set(def.zones.map(z=>f.id+':'+z.id));for(const bore of candidate.features)bore.connects_to=bore.connects_to.filter(t=>!t.startsWith(f.id+':')||valid.has(t));for(const c of candidate.components)if(c.feature_id===f.id)c.status='unconfirmed';}syncNets(candidate);const checked=await post('/api/check-design',candidate);if(JSON.stringify(get())!==baseline)throw Error('Project changed during validation. Reopen the pinned definition.');if(change(()=>set(checked)))dialog.close();};
    const missing=[];for(const f of affected){const old=f.circuits;f.circuits=Object.fromEntries(def.zones.map(z=>[z.id,old[z.id]||'']));for(const z of def.zones)if(!f.circuits[z.id])missing.push([f,z]);}
    if(missing.length){open('Confirm new interface mappings');for(const [f,z]of missing)field(content,f.id+' · '+z.id,'',v=>f.circuits[z.id]=v,{'':'Choose a net',...Object.fromEntries(candidate.nets.map(n=>[n.id,n.id]))});action(content,'Apply mapped definition',guard(apply));}else await apply();
  }));return;}
  action(content,'Save library revision',guard(async()=>{await post('/api/library',def);await library();}));
}
const library=libraryUI(ctx,{open,editor,insert});
projectUI({...ctx,editDefinition:def=>editor(def,true)});
$('library-open').onclick=guard(library);
$('add-port').onclick=()=>{change(()=>{const d=get(),f={id:newId('PORT'),kind:'port',face:'front',u:d.block.length/2,v:d.block.height/2,circuit:d.nets[0]?.id||'P',diameter:12,depth:12,tip_angle:118,clearance_diameter:20,clearance_height:20,connects_to:[],suppressed:false,rotation:0,parent_id:null,local_offset:[0,0],machining_id:'',size:'Custom',port_type:'Demo straight bore',plugged:false,plug_length:8};[f.u,f.v]=clamp(f,d,f.u,f.v);d.features.push(f);select(f.id);});};
function nets(){open('Hydraulic Nets · intent and derived connections');content.append(element('p','Automatic routes connect declared interfaces with orthogonal face drillings. Route length and plug count rank candidates; exact validation decides whether a route is acceptable.'));
  action(content,'Adopt automatic routing (replace manual drillings)',guard(async()=>{const d=await post('/api/adopt-routing',get());change(()=>set(d));nets();}));
  action(content,'Optimize routes with exact checks',guard(async()=>{const button=document.activeElement;button.disabled=true;try{const baseline=JSON.stringify(get());const r=await post('/api/optimize-routes',{design:get(),expected_revision:state().revision,max_attempts:6});if(JSON.stringify(get())!==baseline)throw Error('Draft changed during optimization. Result was not applied; run again from the current draft.');change(()=>set(r.design));nets();content.prepend(element('p',`${r.attempts.length} exact candidates · FAIL ${r.baseline.FAIL} → ${r.final.FAIL} · WARNING ${r.baseline.WARNING} → ${r.final.WARNING}. Evidence ${r.optimization_id}. Save & Validate to commit.`));}finally{button.disabled=false;}}));
  const newNet=element('div',null,'action-row'),name=element('input');name.setAttribute('aria-label','New net ID');name.placeholder='NET_P';newNet.append(name);action(newNet,'Add net',()=>{if(!/^[A-Za-z][A-Za-z0-9_-]{0,39}$/.test(name.value)||get().nets.some(n=>n.id===name.value)){$('workflow-error').textContent='Use a unique engineering ID';return;}change(()=>get().nets.push({id:name.value,label:name.value,members:[],routing:'automatic',diameter:8}));nets();});content.append(newNet);
  for(const n of get().nets){const card=element('section',null,'library-card');content.append(card);card.append(element('h3',n.id),element('p',n.members.join(' ↔ ')||'No interfaces assigned'));const edit=(label,value,fn,o=null,num=false)=>field(card,label,value,v=>change(()=>fn(v)),o,num);
    edit('Routing · '+n.id,n.routing,v=>n.routing=v,{manual:'Manual geometry',automatic:'Automatic from intent'});edit('Drill diameter · '+n.id,n.diameter,v=>n.diameter=v,null,true);edit('First routing axis · '+n.id,n.preferred_axis||'auto',v=>n.preferred_axis=v,{auto:'Compare all axes',x:'X',y:'Y',z:'Z'});edit('Entry preference · '+n.id,n.entry_preference||'nearest',v=>n.entry_preference=v,{nearest:'Nearest / reuse port',negative:'Negative face',positive:'Positive face'});edit('Flow L/min · '+n.id,n.flow_lpm,v=>n.flow_lpm=v,null,true);edit('Pressure bar · '+n.id,n.pressure_bar,v=>n.pressure_bar=v,null,true);
    if(n.routing==='automatic')action(card,'Freeze '+n.id+' geometry for manual override',guard(async()=>{const d=await post('/api/freeze-net',{design:get(),net:n.id});change(()=>set(d));nets();}));
  }
  const route=resolved();if(route){const details=element('details');details.append(element('summary','Inspect generated drilling coordinates'));for(const f of route.features.filter(f=>f.route_net))details.append(element('p',`${f.id} · ${f.route_net} · ${f.face} U${f.u.toFixed(2)} V${f.v.toFixed(2)} · Ø${f.diameter} × ${f.depth.toFixed(2)} · ${f.plugged?'plug':'external port'}`));content.append(details);}
}
$('nets-open').onclick=nets;
function schematic(){open('Schematic assets');content.append(element('p','Attach a PDF, PNG or JPEG to the editable project. Import an AI-generated PMC Project JSON from any provider, then resolve Engineering Review items. This local version does not call an AI service.'));
  const input=element('input');input.type='file';input.accept='.pdf,.png,.jpg,.jpeg';input.setAttribute('aria-label','Upload schematic');content.append(input);input.onchange=guard(async()=>{const f=input.files[0];if(!f)return;const asset=await api('/api/assets',{method:'POST',headers:{'Content-Type':f.type,'X-PMC-Request':'local-console','X-File-Name':encodeURIComponent(f.name)},body:f});change(()=>{if(!get().schematics.some(a=>a.sha256===asset.sha256))get().schematics.push(asset);});schematic();});
  for(const a of get().schematics){const card=element('div',null,'library-card');card.append(element('h3',a.name));const link=element('a','Open local asset');link.href='/api/assets/'+a.sha256;link.target='_blank';link.rel='noopener';card.append(link,element('p','SHA-256 '+a.sha256));if(a.media_type.startsWith('image/')){const img=element('img');img.src=link.href;img.alt=a.name;img.className='schematic-preview';card.append(img);}content.append(card);}
  const components=element('section');components.append(element('h3','Schematic component mapping'));content.append(components);
  for(const c of get().components){const row=element('div',null,'library-card');row.append(element('strong',c.id+' · '+c.function));field(row,'Placed feature · '+c.id,c.feature_id||'',v=>change(()=>{c.feature_id=v||null;}),{'':'Not placed',...Object.fromEntries(get().features.filter(f=>f.kind==='cavity').map(f=>[f.id,f.id]))});field(row,'Confirmation · '+c.id,c.status,v=>change(()=>c.status=v),{unconfirmed:'Unconfirmed',confirmed:'Confirmed by engineer'});row.append(element('p',JSON.stringify(c.ports)));components.append(row);}
  action(components,'Map placed cartridges as schematic components',()=>{change(()=>{for(const f of get().features.filter(f=>f.kind==='cavity'))if(!get().components.some(c=>c.feature_id===f.id))get().components.push({id:f.id,label:f.id,function:'Requires schematic review',cartridge_model:f.cartridge_model,cavity_definition:f.definition,ports:{...f.circuits},feature_id:f.id,status:'unconfirmed'});});schematic();});
  const optional=element('details');optional.append(element('summary','Optional · Codex handoff'));content.append(optional);
  action(optional,'Prepare Codex handoff',guard(async()=>{const h=await post('/api/handoff',{expected_revision:state().revision,design:get()});const box=element('div',null,'library-card');box.append(element('h3','Ready for Codex · awaiting agent'),element('p',h.message));const text=element('textarea');text.value=h.prompt;text.readOnly=true;text.setAttribute('aria-label','Codex handoff prompt');box.append(text);action(box,'Copy Codex prompt',guard(async()=>{await navigator.clipboard.writeText(h.prompt);notice('Handoff prompt copied. Paste it into the current Codex task.');}));content.append(box);}));
}
$('schematic-open').onclick=schematic;
return {editDefinition:def=>editor(def,true)};
}
